// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insert = `-- name: Insert :exec
INSERT INTO audit.log (actor_id, action, data, doc_type, doc_id) VALUES ($1, $2, $3, $4, $5)
`

type InsertParams struct {
	ActorID pgtype.Int8
	Action  string
	Data    []byte
	DocType pgtype.Text
	DocID   pgtype.Int8
}

func (q *Queries) Insert(ctx context.Context, arg InsertParams) error {
	_, err := q.db.Exec(ctx, insert,
		arg.ActorID,
		arg.Action,
		arg.Data,
		arg.DocType,
		arg.DocID,
	)
	return err
}
