// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RecordDocument struct {
	ID             int64
	DocType        string
	Number         string
	Status         string
	Version        int32
	Date           pgtype.Date
	LegalEntityID  int64
	OrgUnitID      int64
	Amount         pgtype.Int8
	Fields         []byte
	ApprovalTicket pgtype.Int8
	SubmittedBy    pgtype.Int8
}
