// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM record.documents WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDocument, id)
	return err
}

const docTypesInUse = `-- name: DocTypesInUse :many
SELECT t::text FROM unnest($1::text[]) AS t
WHERE EXISTS (SELECT 1 FROM record.documents d WHERE d.doc_type = t)
`

func (q *Queries) DocTypesInUse(ctx context.Context, types []string) ([]string, error) {
	rows, err := q.db.Query(ctx, docTypesInUse, types)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var t string
		if err := rows.Scan(&t); err != nil {
			return nil, err
		}
		items = append(items, t)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ensurePeriodLock = `-- name: EnsurePeriodLock :exec
INSERT INTO record.period_locks (legal_entity_id) VALUES ($1) ON CONFLICT DO NOTHING
`

func (q *Queries) EnsurePeriodLock(ctx context.Context, legalEntityID int64) error {
	_, err := q.db.Exec(ctx, ensurePeriodLock, legalEntityID)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, doc_type, number, status, version, date, legal_entity_id, org_unit_id, amount, fields, approval_ticket, submitted_by FROM record.documents WHERE id = $1 AND doc_type = $2
`

type GetDocumentParams struct {
	ID      int64
	DocType string
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (RecordDocument, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.ID, arg.DocType)
	var i RecordDocument
	err := row.Scan(
		&i.ID,
		&i.DocType,
		&i.Number,
		&i.Status,
		&i.Version,
		&i.Date,
		&i.LegalEntityID,
		&i.OrgUnitID,
		&i.Amount,
		&i.Fields,
		&i.ApprovalTicket,
		&i.SubmittedBy,
	)
	return i, err
}

const history = `-- name: History :many
SELECT l.id, l.at, u.name AS actor_name, l.action, l.data
FROM audit.log l LEFT JOIN iam.users u ON u.id = l.actor_id
WHERE l.doc_type = $1 AND l.doc_id = $2
ORDER BY l.at, l.id
`

type HistoryParams struct {
	DocType pgtype.Text
	DocID   pgtype.Int8
}

type HistoryRow struct {
	ID        int64
	At        pgtype.Timestamptz
	ActorName pgtype.Text
	Action    string
	Data      []byte
}

func (q *Queries) History(ctx context.Context, arg HistoryParams) ([]HistoryRow, error) {
	rows, err := q.db.Query(ctx, history, arg.DocType, arg.DocID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HistoryRow
	for rows.Next() {
		var i HistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.ActorName,
			&i.Action,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDocument = `-- name: InsertDocument :one
INSERT INTO record.documents (doc_type, number, status, version, date, legal_entity_id, org_unit_id, amount, fields)
VALUES ($1, $2, 'draft', 1, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertDocumentParams struct {
	DocType       string
	Number        string
	Date          pgtype.Date
	LegalEntityID int64
	OrgUnitID     int64
	Amount        pgtype.Int8
	Fields        []byte
}

func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertDocument,
		arg.DocType,
		arg.Number,
		arg.Date,
		arg.LegalEntityID,
		arg.OrgUnitID,
		arg.Amount,
		arg.Fields,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lockDocument = `-- name: LockDocument :one
SELECT id, doc_type, number, status, version, date, legal_entity_id, org_unit_id, amount, fields, approval_ticket, submitted_by FROM record.documents WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockDocument(ctx context.Context, id int64) (RecordDocument, error) {
	row := q.db.QueryRow(ctx, lockDocument, id)
	var i RecordDocument
	err := row.Scan(
		&i.ID,
		&i.DocType,
		&i.Number,
		&i.Status,
		&i.Version,
		&i.Date,
		&i.LegalEntityID,
		&i.OrgUnitID,
		&i.Amount,
		&i.Fields,
		&i.ApprovalTicket,
		&i.SubmittedBy,
	)
	return i, err
}

const lockPeriodLock = `-- name: LockPeriodLock :one
SELECT locked_until FROM record.period_locks WHERE legal_entity_id = $1 FOR UPDATE
`

func (q *Queries) LockPeriodLock(ctx context.Context, legalEntityID int64) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, lockPeriodLock, legalEntityID)
	var locked_until pgtype.Date
	err := row.Scan(&locked_until)
	return locked_until, err
}

const lockedUntil = `-- name: LockedUntil :many
SELECT locked_until FROM record.period_locks WHERE legal_entity_id = $1
`

// Plain read for allowed_actions; no row means nothing is locked.
func (q *Queries) LockedUntil(ctx context.Context, legalEntityID int64) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, lockedUntil, legalEntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var locked_until pgtype.Date
		if err := rows.Scan(&locked_until); err != nil {
			return nil, err
		}
		items = append(items, locked_until)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const misplacedDocuments = `-- name: MisplacedDocuments :one
WITH RECURSIVE walk AS (
    SELECT id, CASE WHEN kind = 'company' THEN id END AS company FROM iam.org_units WHERE parent_id IS NULL
    UNION ALL
    SELECT u.id, CASE WHEN u.kind = 'company' THEN u.id ELSE w.company END
    FROM iam.org_units u JOIN walk w ON u.parent_id = w.id
)
SELECT count(*) FROM record.documents d JOIN walk w ON w.id = d.org_unit_id
WHERE w.company IS DISTINCT FROM d.legal_entity_id
`

// Documents whose org unit now sits under another legal entity than the one stored.
func (q *Queries) MisplacedDocuments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, misplacedDocuments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const pendingInPeriod = `-- name: PendingInPeriod :many
SELECT id, doc_type, number, date FROM record.documents
WHERE legal_entity_id = $1 AND status = 'pending_approval' AND date <= $2
ORDER BY date, id
`

type PendingInPeriodParams struct {
	LegalEntityID int64
	Date          pgtype.Date
}

type PendingInPeriodRow struct {
	ID      int64
	DocType string
	Number  string
	Date    pgtype.Date
}

func (q *Queries) PendingInPeriod(ctx context.Context, arg PendingInPeriodParams) ([]PendingInPeriodRow, error) {
	rows, err := q.db.Query(ctx, pendingInPeriod, arg.LegalEntityID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingInPeriodRow
	for rows.Next() {
		var i PendingInPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.DocType,
			&i.Number,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const periodLocks = `-- name: PeriodLocks :many
SELECT u.id, u.name, p.locked_until FROM iam.org_units u
LEFT JOIN record.period_locks p ON p.legal_entity_id = u.id
WHERE u.kind = 'company' ORDER BY u.name, u.id
`

type PeriodLocksRow struct {
	ID          int64
	Name        string
	LockedUntil pgtype.Date
}

func (q *Queries) PeriodLocks(ctx context.Context) ([]PeriodLocksRow, error) {
	rows, err := q.db.Query(ctx, periodLocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeriodLocksRow
	for rows.Next() {
		var i PeriodLocksRow
		if err := rows.Scan(&i.ID, &i.Name, &i.LockedUntil); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLockedUntil = `-- name: SetLockedUntil :exec
UPDATE record.period_locks SET locked_until = $2 WHERE legal_entity_id = $1
`

type SetLockedUntilParams struct {
	LegalEntityID int64
	LockedUntil   pgtype.Date
}

func (q *Queries) SetLockedUntil(ctx context.Context, arg SetLockedUntilParams) error {
	_, err := q.db.Exec(ctx, setLockedUntil, arg.LegalEntityID, arg.LockedUntil)
	return err
}

const setStatus = `-- name: SetStatus :exec
UPDATE record.documents SET status = $1, approval_ticket = $2, submitted_by = $3,
    version = version + $4::int
WHERE id = $5
`

type SetStatusParams struct {
	Status         string
	ApprovalTicket pgtype.Int8
	SubmittedBy    pgtype.Int8
	Bump           int32
	ID             int64
}

// Sending for approval keeps the version, so the approval instance can compare it.
func (q *Queries) SetStatus(ctx context.Context, arg SetStatusParams) error {
	_, err := q.db.Exec(ctx, setStatus,
		arg.Status,
		arg.ApprovalTicket,
		arg.SubmittedBy,
		arg.Bump,
		arg.ID,
	)
	return err
}

const sharePeriodLock = `-- name: SharePeriodLock :one
SELECT locked_until FROM record.period_locks WHERE legal_entity_id = $1 FOR SHARE
`

func (q *Queries) SharePeriodLock(ctx context.Context, legalEntityID int64) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, sharePeriodLock, legalEntityID)
	var locked_until pgtype.Date
	err := row.Scan(&locked_until)
	return locked_until, err
}

const updateHeader = `-- name: UpdateHeader :exec
UPDATE record.documents SET date = $2, org_unit_id = $3, amount = $4, fields = $5, version = version + 1
WHERE id = $1
`

type UpdateHeaderParams struct {
	ID        int64
	Date      pgtype.Date
	OrgUnitID int64
	Amount    pgtype.Int8
	Fields    []byte
}

func (q *Queries) UpdateHeader(ctx context.Context, arg UpdateHeaderParams) error {
	_, err := q.db.Exec(ctx, updateHeader,
		arg.ID,
		arg.Date,
		arg.OrgUnitID,
		arg.Amount,
		arg.Fields,
	)
	return err
}
