// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertLines = `-- name: InsertLines :exec
INSERT INTO posting.lines (doc_type, doc_id, legal_entity_id, date, kind, org_unit_id, amount)
SELECT $1::text, $2::bigint, $3::bigint, $4::date,
       unnest($5::text[]), unnest($6::bigint[]), unnest($7::bigint[])
`

type InsertLinesParams struct {
	DocType       string
	DocID         int64
	LegalEntityID int64
	Date          pgtype.Date
	Kinds         []string
	OrgUnitIds    []int64
	Amounts       []int64
}

func (q *Queries) InsertLines(ctx context.Context, arg InsertLinesParams) error {
	_, err := q.db.Exec(ctx, insertLines,
		arg.DocType,
		arg.DocID,
		arg.LegalEntityID,
		arg.Date,
		arg.Kinds,
		arg.OrgUnitIds,
		arg.Amounts,
	)
	return err
}

const voidLines = `-- name: VoidLines :exec
UPDATE posting.lines SET voided_at = now() WHERE doc_type = $1 AND doc_id = $2 AND voided_at IS NULL
`

type VoidLinesParams struct {
	DocType string
	DocID   int64
}

func (q *Queries) VoidLines(ctx context.Context, arg VoidLinesParams) error {
	_, err := q.db.Exec(ctx, voidLines, arg.DocType, arg.DocID)
	return err
}
