// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type HrmContractType struct {
	ID        int64
	Name      string
	Active    bool
	FixedTerm bool
}

type HrmEmployee struct {
	ID                int64
	Code              string
	FullName          string
	DateOfBirth       pgtype.Date
	Gender            pgtype.Text
	Phone             pgtype.Text
	Email             pgtype.Text
	Address           pgtype.Text
	OrgUnitID         int64
	ManagerID         pgtype.Int8
	UserID            pgtype.Int8
	HireDate          pgtype.Date
	TerminationDate   pgtype.Date
	NationalID        []byte
	SocialInsuranceNo []byte
	TaxCode           []byte
	BankAccount       []byte
}

type HrmLeaveType struct {
	ID             int64
	Name           string
	DeductsBalance bool
	Active         bool
	Paid           bool
}

type HrmLegalParam struct {
	Key           string
	EffectiveFrom pgtype.Date
	Value         string
}
