// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addLeaveBalance = `-- name: AddLeaveBalance :one
UPDATE hrm.leave_balances SET days = days + CAST($1::text AS numeric)
WHERE employee_id = $2 AND year = $3
RETURNING days::text
`

type AddLeaveBalanceParams struct {
	Delta      string
	EmployeeID int64
	Year       int32
}

// Locks the row until commit; a negative result fails leave_balances_days_check.
func (q *Queries) AddLeaveBalance(ctx context.Context, arg AddLeaveBalanceParams) (string, error) {
	row := q.db.QueryRow(ctx, addLeaveBalance, arg.Delta, arg.EmployeeID, arg.Year)
	var days string
	err := row.Scan(&days)
	return days, err
}

const anyEmployee = `-- name: AnyEmployee :one
SELECT EXISTS (SELECT 1 FROM hrm.employees)
`

func (q *Queries) AnyEmployee(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, anyEmployee)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const clearPayrollComputed = `-- name: ClearPayrollComputed :exec
UPDATE hrm.payrolls SET computed_at = NULL WHERE id = $1
`

func (q *Queries) ClearPayrollComputed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, clearPayrollComputed, id)
	return err
}

const closedPeriods = `-- name: ClosedPeriods :many
SELECT period_start, period_end FROM hrm.payroll_periods
WHERE legal_entity_id = $1 AND posted_payroll_id IS NOT NULL
  AND period_end >= $2::date AND ($3::date IS NULL OR period_start <= $3)
ORDER BY period_start
`

type ClosedPeriodsParams struct {
	LegalEntityID int64
	FromDate      pgtype.Date
	ToDate        pgtype.Date
}

type ClosedPeriodsRow struct {
	PeriodStart pgtype.Date
	PeriodEnd   pgtype.Date
}

// Closed periods of the legal entity overlapping [@from, @to]; a null @to is open-ended.
func (q *Queries) ClosedPeriods(ctx context.Context, arg ClosedPeriodsParams) ([]ClosedPeriodsRow, error) {
	rows, err := q.db.Query(ctx, closedPeriods, arg.LegalEntityID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClosedPeriodsRow
	for rows.Next() {
		var i ClosedPeriodsRow
		if err := rows.Scan(&i.PeriodStart, &i.PeriodEnd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contractOverlaps = `-- name: ContractOverlaps :one
SELECT EXISTS (
    SELECT 1 FROM hrm.contracts c JOIN record.documents d ON d.id = c.id
    WHERE c.employee_id = $1 AND c.id <> $2 AND c.parent_id IS NULL AND d.status = 'posted'
      AND daterange(c.start_date, c.end_date, '[]') && daterange($3::date, $4::date, '[]')
)
`

type ContractOverlapsParams struct {
	EmployeeID int64
	ID         int64
	StartDate  pgtype.Date
	EndDate    pgtype.Date
}

// Whether another posted original of the employee overlaps [@start, @end] (null end: open-ended).
func (q *Queries) ContractOverlaps(ctx context.Context, arg ContractOverlapsParams) (bool, error) {
	row := q.db.QueryRow(ctx, contractOverlaps,
		arg.EmployeeID,
		arg.ID,
		arg.StartDate,
		arg.EndDate,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const contractTermsAt = `-- name: ContractTermsAt :one
SELECT coalesce(a.id, c.id)::bigint AS id, coalesce(a.terms, c.terms)::bytea AS terms
FROM hrm.contracts c JOIN record.documents d ON d.id = c.id
LEFT JOIN LATERAL (
    SELECT x.id, x.terms FROM hrm.contracts x JOIN record.documents xd ON xd.id = x.id
    WHERE x.parent_id = c.id AND xd.status = 'posted' AND x.start_date <= $1::date
    ORDER BY x.start_date DESC, x.id DESC LIMIT 1
) a ON true
WHERE c.employee_id = $2 AND c.parent_id IS NULL AND d.status = 'posted'
  AND c.start_date <= $1 AND (c.end_date IS NULL OR c.end_date >= $1)
`

type ContractTermsAtParams struct {
	At         pgtype.Date
	EmployeeID int64
}

type ContractTermsAtRow struct {
	ID    int64
	Terms []byte
}

// The terms in force at @at, and the contract holding them: the posted original covering
// it, or its latest posted appendix effective by then.
func (q *Queries) ContractTermsAt(ctx context.Context, arg ContractTermsAtParams) (ContractTermsAtRow, error) {
	row := q.db.QueryRow(ctx, contractTermsAt, arg.At, arg.EmployeeID)
	var i ContractTermsAtRow
	err := row.Scan(&i.ID, &i.Terms)
	return i, err
}

const createContract = `-- name: CreateContract :exec
INSERT INTO hrm.contracts (id, employee_id, contract_type_id, parent_id, start_date, end_date, terms)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateContractParams struct {
	ID             int64
	EmployeeID     int64
	ContractTypeID int64
	ParentID       pgtype.Int8
	StartDate      pgtype.Date
	EndDate        pgtype.Date
	Terms          []byte
}

func (q *Queries) CreateContract(ctx context.Context, arg CreateContractParams) error {
	_, err := q.db.Exec(ctx, createContract,
		arg.ID,
		arg.EmployeeID,
		arg.ContractTypeID,
		arg.ParentID,
		arg.StartDate,
		arg.EndDate,
		arg.Terms,
	)
	return err
}

const createContractType = `-- name: CreateContractType :one
INSERT INTO hrm.contract_types (name, fixed_term, active) VALUES ($1, $2, $3) RETURNING id
`

type CreateContractTypeParams struct {
	Name      string
	FixedTerm bool
	Active    bool
}

func (q *Queries) CreateContractType(ctx context.Context, arg CreateContractTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, createContractType, arg.Name, arg.FixedTerm, arg.Active)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createDependent = `-- name: CreateDependent :one
INSERT INTO hrm.dependents (employee_id, data) VALUES ($1, $2) RETURNING id
`

type CreateDependentParams struct {
	EmployeeID int64
	Data       []byte
}

func (q *Queries) CreateDependent(ctx context.Context, arg CreateDependentParams) (int64, error) {
	row := q.db.QueryRow(ctx, createDependent, arg.EmployeeID, arg.Data)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO hrm.employees (code, full_name, date_of_birth, gender, phone, email, address, org_unit_id,
                           manager_id, user_id, hire_date, termination_date,
                           national_id, social_insurance_no, tax_code, bank_account)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id
`

type CreateEmployeeParams struct {
	Code              string
	FullName          string
	DateOfBirth       pgtype.Date
	Gender            pgtype.Text
	Phone             pgtype.Text
	Email             pgtype.Text
	Address           pgtype.Text
	OrgUnitID         int64
	ManagerID         pgtype.Int8
	UserID            pgtype.Int8
	HireDate          pgtype.Date
	TerminationDate   pgtype.Date
	NationalID        []byte
	SocialInsuranceNo []byte
	TaxCode           []byte
	BankAccount       []byte
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (int64, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.Code,
		arg.FullName,
		arg.DateOfBirth,
		arg.Gender,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.OrgUnitID,
		arg.ManagerID,
		arg.UserID,
		arg.HireDate,
		arg.TerminationDate,
		arg.NationalID,
		arg.SocialInsuranceNo,
		arg.TaxCode,
		arg.BankAccount,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createLeaveRequest = `-- name: CreateLeaveRequest :exec
INSERT INTO hrm.leave_requests (id, employee_id, leave_type_id, start_date, end_date, days, reason)
VALUES ($1, $2, $3, $4, $5, CAST($6::text AS numeric), $7)
`

type CreateLeaveRequestParams struct {
	ID          int64
	EmployeeID  int64
	LeaveTypeID int64
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	Days        string
	Reason      pgtype.Text
}

func (q *Queries) CreateLeaveRequest(ctx context.Context, arg CreateLeaveRequestParams) error {
	_, err := q.db.Exec(ctx, createLeaveRequest,
		arg.ID,
		arg.EmployeeID,
		arg.LeaveTypeID,
		arg.StartDate,
		arg.EndDate,
		arg.Days,
		arg.Reason,
	)
	return err
}

const createLeaveType = `-- name: CreateLeaveType :one
INSERT INTO hrm.leave_types (name, deducts_balance, paid, active) VALUES ($1, $2, $3, $4) RETURNING id
`

type CreateLeaveTypeParams struct {
	Name           string
	DeductsBalance bool
	Paid           bool
	Active         bool
}

func (q *Queries) CreateLeaveType(ctx context.Context, arg CreateLeaveTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, createLeaveType,
		arg.Name,
		arg.DeductsBalance,
		arg.Paid,
		arg.Active,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createOvertimeRequest = `-- name: CreateOvertimeRequest :exec
INSERT INTO hrm.overtime_requests (id, employee_id, date, day_kind, day_hours, night_hours, reason)
VALUES ($1, $2, $3, $4, CAST($5::text AS numeric), CAST($6::text AS numeric), $7)
`

type CreateOvertimeRequestParams struct {
	ID         int64
	EmployeeID int64
	Date       pgtype.Date
	DayKind    string
	DayHours   string
	NightHours string
	Reason     pgtype.Text
}

func (q *Queries) CreateOvertimeRequest(ctx context.Context, arg CreateOvertimeRequestParams) error {
	_, err := q.db.Exec(ctx, createOvertimeRequest,
		arg.ID,
		arg.EmployeeID,
		arg.Date,
		arg.DayKind,
		arg.DayHours,
		arg.NightHours,
		arg.Reason,
	)
	return err
}

const createPayroll = `-- name: CreatePayroll :exec
INSERT INTO hrm.payrolls (id, period_start, period_end) VALUES ($1, $2, $3)
`

type CreatePayrollParams struct {
	ID          int64
	PeriodStart pgtype.Date
	PeriodEnd   pgtype.Date
}

func (q *Queries) CreatePayroll(ctx context.Context, arg CreatePayrollParams) error {
	_, err := q.db.Exec(ctx, createPayroll, arg.ID, arg.PeriodStart, arg.PeriodEnd)
	return err
}

const createTimesheet = `-- name: CreateTimesheet :exec
INSERT INTO hrm.timesheets (id, org_unit_id, period_start, period_end) VALUES ($1, $2, $3, $4)
`

type CreateTimesheetParams struct {
	ID          int64
	OrgUnitID   int64
	PeriodStart pgtype.Date
	PeriodEnd   pgtype.Date
}

func (q *Queries) CreateTimesheet(ctx context.Context, arg CreateTimesheetParams) error {
	_, err := q.db.Exec(ctx, createTimesheet,
		arg.ID,
		arg.OrgUnitID,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	return err
}

const deactivateTimesheet = `-- name: DeactivateTimesheet :exec
UPDATE hrm.timesheets SET active = false WHERE id = $1
`

func (q *Queries) DeactivateTimesheet(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateTimesheet, id)
	return err
}

const deleteContract = `-- name: DeleteContract :exec
DELETE FROM hrm.contracts WHERE id = $1
`

func (q *Queries) DeleteContract(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteContract, id)
	return err
}

const deleteDependent = `-- name: DeleteDependent :exec
DELETE FROM hrm.dependents WHERE id = $1 AND employee_id = $2
`

type DeleteDependentParams struct {
	ID         int64
	EmployeeID int64
}

func (q *Queries) DeleteDependent(ctx context.Context, arg DeleteDependentParams) error {
	_, err := q.db.Exec(ctx, deleteDependent, arg.ID, arg.EmployeeID)
	return err
}

const deleteHoliday = `-- name: DeleteHoliday :execrows
DELETE FROM hrm.holidays WHERE legal_entity_id = $1 AND date = $2
`

type DeleteHolidayParams struct {
	LegalEntityID int64
	Date          pgtype.Date
}

func (q *Queries) DeleteHoliday(ctx context.Context, arg DeleteHolidayParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHoliday, arg.LegalEntityID, arg.Date)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLeaveRequest = `-- name: DeleteLeaveRequest :exec
DELETE FROM hrm.leave_requests WHERE id = $1
`

func (q *Queries) DeleteLeaveRequest(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLeaveRequest, id)
	return err
}

const deleteOvertimeRequest = `-- name: DeleteOvertimeRequest :exec
DELETE FROM hrm.overtime_requests WHERE id = $1
`

func (q *Queries) DeleteOvertimeRequest(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteOvertimeRequest, id)
	return err
}

const deletePayroll = `-- name: DeletePayroll :exec
DELETE FROM hrm.payrolls WHERE id = $1
`

func (q *Queries) DeletePayroll(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePayroll, id)
	return err
}

const deletePayrollAdjustments = `-- name: DeletePayrollAdjustments :exec
DELETE FROM hrm.payroll_adjustments WHERE payroll_id = $1
`

func (q *Queries) DeletePayrollAdjustments(ctx context.Context, payrollID int64) error {
	_, err := q.db.Exec(ctx, deletePayrollAdjustments, payrollID)
	return err
}

const deletePayrollLines = `-- name: DeletePayrollLines :exec
DELETE FROM hrm.payroll_lines WHERE payroll_id = $1
`

func (q *Queries) DeletePayrollLines(ctx context.Context, payrollID int64) error {
	_, err := q.db.Exec(ctx, deletePayrollLines, payrollID)
	return err
}

const deletePayrollSources = `-- name: DeletePayrollSources :exec
DELETE FROM hrm.payroll_sources WHERE payroll_id = $1
`

func (q *Queries) DeletePayrollSources(ctx context.Context, payrollID int64) error {
	_, err := q.db.Exec(ctx, deletePayrollSources, payrollID)
	return err
}

const deleteTimesheet = `-- name: DeleteTimesheet :exec
DELETE FROM hrm.timesheets WHERE id = $1
`

func (q *Queries) DeleteTimesheet(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTimesheet, id)
	return err
}

const deleteTimesheetLines = `-- name: DeleteTimesheetLines :exec
DELETE FROM hrm.timesheet_lines WHERE timesheet_id = $1
`

func (q *Queries) DeleteTimesheetLines(ctx context.Context, timesheetID int64) error {
	_, err := q.db.Exec(ctx, deleteTimesheetLines, timesheetID)
	return err
}

const deleteWorkWeek = `-- name: DeleteWorkWeek :execrows
DELETE FROM hrm.work_weeks WHERE legal_entity_id = $1 AND effective_from = $2
`

type DeleteWorkWeekParams struct {
	LegalEntityID int64
	EffectiveFrom pgtype.Date
}

func (q *Queries) DeleteWorkWeek(ctx context.Context, arg DeleteWorkWeekParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkWeek, arg.LegalEntityID, arg.EffectiveFrom)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const employeeByUser = `-- name: EmployeeByUser :one
SELECT id, full_name, org_unit_id FROM hrm.employees WHERE user_id = $1
`

type EmployeeByUserRow struct {
	ID        int64
	FullName  string
	OrgUnitID int64
}

func (q *Queries) EmployeeByUser(ctx context.Context, userID pgtype.Int8) (EmployeeByUserRow, error) {
	row := q.db.QueryRow(ctx, employeeByUser, userID)
	var i EmployeeByUserRow
	err := row.Scan(&i.ID, &i.FullName, &i.OrgUnitID)
	return i, err
}

const employeesByCodes = `-- name: EmployeesByCodes :many
SELECT id, code, org_unit_id FROM hrm.employees WHERE lower(code) = ANY($1::text[])
`

type EmployeesByCodesRow struct {
	ID        int64
	Code      string
	OrgUnitID int64
}

func (q *Queries) EmployeesByCodes(ctx context.Context, codes []string) ([]EmployeesByCodesRow, error) {
	rows, err := q.db.Query(ctx, employeesByCodes, codes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmployeesByCodesRow
	for rows.Next() {
		var i EmployeesByCodesRow
		if err := rows.Scan(&i.ID, &i.Code, &i.OrgUnitID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ensureLeaveBalance = `-- name: EnsureLeaveBalance :exec
INSERT INTO hrm.leave_balances (employee_id, year, days) VALUES ($1, $2, 0) ON CONFLICT DO NOTHING
`

type EnsureLeaveBalanceParams struct {
	EmployeeID int64
	Year       int32
}

func (q *Queries) EnsureLeaveBalance(ctx context.Context, arg EnsureLeaveBalanceParams) error {
	_, err := q.db.Exec(ctx, ensureLeaveBalance, arg.EmployeeID, arg.Year)
	return err
}

const ensurePayrollLock = `-- name: EnsurePayrollLock :exec
INSERT INTO hrm.payroll_locks (legal_entity_id) VALUES ($1) ON CONFLICT DO NOTHING
`

func (q *Queries) EnsurePayrollLock(ctx context.Context, legalEntityID int64) error {
	_, err := q.db.Exec(ctx, ensurePayrollLock, legalEntityID)
	return err
}

const ensurePayrollPeriod = `-- name: EnsurePayrollPeriod :exec
INSERT INTO hrm.payroll_periods (legal_entity_id, period_start, period_end) VALUES ($1, $2, $3)
ON CONFLICT (legal_entity_id, period_start) DO NOTHING
`

type EnsurePayrollPeriodParams struct {
	LegalEntityID int64
	PeriodStart   pgtype.Date
	PeriodEnd     pgtype.Date
}

func (q *Queries) EnsurePayrollPeriod(ctx context.Context, arg EnsurePayrollPeriodParams) error {
	_, err := q.db.Exec(ctx, ensurePayrollPeriod, arg.LegalEntityID, arg.PeriodStart, arg.PeriodEnd)
	return err
}

const getContract = `-- name: GetContract :one
SELECT c.id, c.employee_id, c.contract_type_id, c.parent_id, c.start_date, c.end_date, c.terms,
       e.code AS employee_code, e.full_name AS employee_name, e.user_id AS employee_user_id,
       t.name AS contract_type_name, d.org_unit_id,
       p.parent_id AS parent_parent_id, p.start_date AS parent_start, p.end_date AS parent_end,
       pd.number AS parent_number, pd.status AS parent_status
FROM hrm.contracts c
JOIN hrm.employees e ON e.id = c.employee_id
JOIN hrm.contract_types t ON t.id = c.contract_type_id
JOIN record.documents d ON d.id = c.id
LEFT JOIN hrm.contracts p ON p.id = c.parent_id
LEFT JOIN record.documents pd ON pd.id = c.parent_id
WHERE c.id = $1
`

type GetContractRow struct {
	ID               int64
	EmployeeID       int64
	ContractTypeID   int64
	ParentID         pgtype.Int8
	StartDate        pgtype.Date
	EndDate          pgtype.Date
	Terms            []byte
	EmployeeCode     string
	EmployeeName     string
	EmployeeUserID   pgtype.Int8
	ContractTypeName string
	OrgUnitID        int64
	ParentParentID   pgtype.Int8
	ParentStart      pgtype.Date
	ParentEnd        pgtype.Date
	ParentNumber     pgtype.Text
	ParentStatus     pgtype.Text
}

func (q *Queries) GetContract(ctx context.Context, id int64) (GetContractRow, error) {
	row := q.db.QueryRow(ctx, getContract, id)
	var i GetContractRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.ContractTypeID,
		&i.ParentID,
		&i.StartDate,
		&i.EndDate,
		&i.Terms,
		&i.EmployeeCode,
		&i.EmployeeName,
		&i.EmployeeUserID,
		&i.ContractTypeName,
		&i.OrgUnitID,
		&i.ParentParentID,
		&i.ParentStart,
		&i.ParentEnd,
		&i.ParentNumber,
		&i.ParentStatus,
	)
	return i, err
}

const getContractType = `-- name: GetContractType :one
SELECT id, name, active, fixed_term FROM hrm.contract_types WHERE id = $1
`

func (q *Queries) GetContractType(ctx context.Context, id int64) (HrmContractType, error) {
	row := q.db.QueryRow(ctx, getContractType, id)
	var i HrmContractType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.FixedTerm,
	)
	return i, err
}

const getDependent = `-- name: GetDependent :one
SELECT data FROM hrm.dependents WHERE id = $1 AND employee_id = $2 FOR UPDATE
`

type GetDependentParams struct {
	ID         int64
	EmployeeID int64
}

func (q *Queries) GetDependent(ctx context.Context, arg GetDependentParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getDependent, arg.ID, arg.EmployeeID)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const getEmployee = `-- name: GetEmployee :one
SELECT e.id, e.code, e.full_name, e.date_of_birth, e.gender, e.phone, e.email, e.address, e.org_unit_id, e.manager_id, e.user_id, e.hire_date, e.termination_date, e.national_id, e.social_insurance_no, e.tax_code, e.bank_account, u.name AS org_unit_name, m.code AS manager_code, m.full_name AS manager_name, a.login AS user_login
FROM hrm.employees e
JOIN iam.org_units u ON u.id = e.org_unit_id
LEFT JOIN hrm.employees m ON m.id = e.manager_id
LEFT JOIN iam.users a ON a.id = e.user_id
WHERE e.id = $1
`

type GetEmployeeRow struct {
	ID                int64
	Code              string
	FullName          string
	DateOfBirth       pgtype.Date
	Gender            pgtype.Text
	Phone             pgtype.Text
	Email             pgtype.Text
	Address           pgtype.Text
	OrgUnitID         int64
	ManagerID         pgtype.Int8
	UserID            pgtype.Int8
	HireDate          pgtype.Date
	TerminationDate   pgtype.Date
	NationalID        []byte
	SocialInsuranceNo []byte
	TaxCode           []byte
	BankAccount       []byte
	OrgUnitName       string
	ManagerCode       pgtype.Text
	ManagerName       pgtype.Text
	UserLogin         pgtype.Text
}

func (q *Queries) GetEmployee(ctx context.Context, id int64) (GetEmployeeRow, error) {
	row := q.db.QueryRow(ctx, getEmployee, id)
	var i GetEmployeeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.FullName,
		&i.DateOfBirth,
		&i.Gender,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.OrgUnitID,
		&i.ManagerID,
		&i.UserID,
		&i.HireDate,
		&i.TerminationDate,
		&i.NationalID,
		&i.SocialInsuranceNo,
		&i.TaxCode,
		&i.BankAccount,
		&i.OrgUnitName,
		&i.ManagerCode,
		&i.ManagerName,
		&i.UserLogin,
	)
	return i, err
}

const getLeaveRequest = `-- name: GetLeaveRequest :one
SELECT r.id, r.employee_id, r.leave_type_id, r.start_date, r.end_date, r.days::text AS days, r.reason,
       r.deducted::text AS deducted,
       e.code AS employee_code, e.full_name AS employee_name, e.user_id AS employee_user_id,
       t.name AS leave_type_name, t.deducts_balance, d.org_unit_id
FROM hrm.leave_requests r
JOIN hrm.employees e ON e.id = r.employee_id
JOIN hrm.leave_types t ON t.id = r.leave_type_id
JOIN record.documents d ON d.id = r.id
WHERE r.id = $1
`

type GetLeaveRequestRow struct {
	ID             int64
	EmployeeID     int64
	LeaveTypeID    int64
	StartDate      pgtype.Date
	EndDate        pgtype.Date
	Days           string
	Reason         pgtype.Text
	Deducted       string
	EmployeeCode   string
	EmployeeName   string
	EmployeeUserID pgtype.Int8
	LeaveTypeName  string
	DeductsBalance bool
	OrgUnitID      int64
}

func (q *Queries) GetLeaveRequest(ctx context.Context, id int64) (GetLeaveRequestRow, error) {
	row := q.db.QueryRow(ctx, getLeaveRequest, id)
	var i GetLeaveRequestRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LeaveTypeID,
		&i.StartDate,
		&i.EndDate,
		&i.Days,
		&i.Reason,
		&i.Deducted,
		&i.EmployeeCode,
		&i.EmployeeName,
		&i.EmployeeUserID,
		&i.LeaveTypeName,
		&i.DeductsBalance,
		&i.OrgUnitID,
	)
	return i, err
}

const getLeaveType = `-- name: GetLeaveType :one
SELECT id, name, deducts_balance, active, paid FROM hrm.leave_types WHERE id = $1
`

func (q *Queries) GetLeaveType(ctx context.Context, id int64) (HrmLeaveType, error) {
	row := q.db.QueryRow(ctx, getLeaveType, id)
	var i HrmLeaveType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeductsBalance,
		&i.Active,
		&i.Paid,
	)
	return i, err
}

const getLegalParam = `-- name: GetLegalParam :one
SELECT value FROM hrm.legal_params WHERE key = $1 AND effective_from = $2
`

type GetLegalParamParams struct {
	Key           string
	EffectiveFrom pgtype.Date
}

func (q *Queries) GetLegalParam(ctx context.Context, arg GetLegalParamParams) (string, error) {
	row := q.db.QueryRow(ctx, getLegalParam, arg.Key, arg.EffectiveFrom)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getOvertimeRequest = `-- name: GetOvertimeRequest :one
SELECT r.id, r.employee_id, r.date, r.day_kind, r.day_hours::text AS day_hours, r.night_hours::text AS night_hours, r.reason,
       e.code AS employee_code, e.full_name AS employee_name, e.user_id AS employee_user_id, d.org_unit_id
FROM hrm.overtime_requests r
JOIN hrm.employees e ON e.id = r.employee_id
JOIN record.documents d ON d.id = r.id
WHERE r.id = $1
`

type GetOvertimeRequestRow struct {
	ID             int64
	EmployeeID     int64
	Date           pgtype.Date
	DayKind        string
	DayHours       string
	NightHours     string
	Reason         pgtype.Text
	EmployeeCode   string
	EmployeeName   string
	EmployeeUserID pgtype.Int8
	OrgUnitID      int64
}

func (q *Queries) GetOvertimeRequest(ctx context.Context, id int64) (GetOvertimeRequestRow, error) {
	row := q.db.QueryRow(ctx, getOvertimeRequest, id)
	var i GetOvertimeRequestRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Date,
		&i.DayKind,
		&i.DayHours,
		&i.NightHours,
		&i.Reason,
		&i.EmployeeCode,
		&i.EmployeeName,
		&i.EmployeeUserID,
		&i.OrgUnitID,
	)
	return i, err
}

const getPayroll = `-- name: GetPayroll :one
SELECT p.id, p.period_start, p.period_end, p.computed_at, p.inputs_hash, d.legal_entity_id, u.name AS legal_entity_name
FROM hrm.payrolls p
JOIN record.documents d ON d.id = p.id
JOIN iam.org_units u ON u.id = d.legal_entity_id
WHERE p.id = $1
`

type GetPayrollRow struct {
	ID              int64
	PeriodStart     pgtype.Date
	PeriodEnd       pgtype.Date
	ComputedAt      pgtype.Timestamptz
	InputsHash      []byte
	LegalEntityID   int64
	LegalEntityName string
}

func (q *Queries) GetPayroll(ctx context.Context, id int64) (GetPayrollRow, error) {
	row := q.db.QueryRow(ctx, getPayroll, id)
	var i GetPayrollRow
	err := row.Scan(
		&i.ID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.ComputedAt,
		&i.InputsHash,
		&i.LegalEntityID,
		&i.LegalEntityName,
	)
	return i, err
}

const getTimesheet = `-- name: GetTimesheet :one
SELECT t.id, t.org_unit_id, t.period_start, t.period_end, t.active, u.name AS org_unit_name
FROM hrm.timesheets t
JOIN iam.org_units u ON u.id = t.org_unit_id
WHERE t.id = $1
`

type GetTimesheetRow struct {
	ID          int64
	OrgUnitID   int64
	PeriodStart pgtype.Date
	PeriodEnd   pgtype.Date
	Active      bool
	OrgUnitName string
}

func (q *Queries) GetTimesheet(ctx context.Context, id int64) (GetTimesheetRow, error) {
	row := q.db.QueryRow(ctx, getTimesheet, id)
	var i GetTimesheetRow
	err := row.Scan(
		&i.ID,
		&i.OrgUnitID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Active,
		&i.OrgUnitName,
	)
	return i, err
}

const hasPostedAppendix = `-- name: HasPostedAppendix :one
SELECT EXISTS (
    SELECT 1 FROM hrm.contracts c JOIN record.documents d ON d.id = c.id
    WHERE c.parent_id = $1 AND d.status = 'posted'
)
`

func (q *Queries) HasPostedAppendix(ctx context.Context, parentID pgtype.Int8) (bool, error) {
	row := q.db.QueryRow(ctx, hasPostedAppendix, parentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const holidays = `-- name: Holidays :many
SELECT date, name FROM hrm.holidays
WHERE legal_entity_id = $1 AND date BETWEEN $2::date AND $3::date ORDER BY date
`

type HolidaysParams struct {
	LegalEntityID int64
	FromDate      pgtype.Date
	ToDate        pgtype.Date
}

type HolidaysRow struct {
	Date pgtype.Date
	Name string
}

func (q *Queries) Holidays(ctx context.Context, arg HolidaysParams) ([]HolidaysRow, error) {
	rows, err := q.db.Query(ctx, holidays, arg.LegalEntityID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HolidaysRow
	for rows.Next() {
		var i HolidaysRow
		if err := rows.Scan(&i.Date, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPayrollAdjustment = `-- name: InsertPayrollAdjustment :exec
INSERT INTO hrm.payroll_adjustments (payroll_id, employee_id, source_period, data) VALUES ($1, $2, $3, $4)
`

type InsertPayrollAdjustmentParams struct {
	PayrollID    int64
	EmployeeID   int64
	SourcePeriod pgtype.Date
	Data         []byte
}

func (q *Queries) InsertPayrollAdjustment(ctx context.Context, arg InsertPayrollAdjustmentParams) error {
	_, err := q.db.Exec(ctx, insertPayrollAdjustment,
		arg.PayrollID,
		arg.EmployeeID,
		arg.SourcePeriod,
		arg.Data,
	)
	return err
}

const insertPayrollLine = `-- name: InsertPayrollLine :exec
INSERT INTO hrm.payroll_lines (payroll_id, employee_id, org_unit_id, data) VALUES ($1, $2, $3, $4)
`

type InsertPayrollLineParams struct {
	PayrollID  int64
	EmployeeID int64
	OrgUnitID  int64
	Data       []byte
}

func (q *Queries) InsertPayrollLine(ctx context.Context, arg InsertPayrollLineParams) error {
	_, err := q.db.Exec(ctx, insertPayrollLine,
		arg.PayrollID,
		arg.EmployeeID,
		arg.OrgUnitID,
		arg.Data,
	)
	return err
}

const insertPayrollSources = `-- name: InsertPayrollSources :exec
INSERT INTO hrm.payroll_sources (payroll_id, doc_type, doc_id, version)
SELECT $1::bigint, unnest($2::text[]), unnest($3::bigint[]), unnest($4::int[])
`

type InsertPayrollSourcesParams struct {
	PayrollID int64
	DocTypes  []string
	DocIds    []int64
	Versions  []int32
}

func (q *Queries) InsertPayrollSources(ctx context.Context, arg InsertPayrollSourcesParams) error {
	_, err := q.db.Exec(ctx, insertPayrollSources,
		arg.PayrollID,
		arg.DocTypes,
		arg.DocIds,
		arg.Versions,
	)
	return err
}

const insertTimesheetLines = `-- name: InsertTimesheetLines :exec
INSERT INTO hrm.timesheet_lines (timesheet_id, employee_id, date, days)
SELECT $1::bigint, unnest($2::bigint[]), unnest($3::date[]), unnest($4::text[])::numeric
`

type InsertTimesheetLinesParams struct {
	TimesheetID int64
	EmployeeIds []int64
	Dates       []pgtype.Date
	Days        []string
}

func (q *Queries) InsertTimesheetLines(ctx context.Context, arg InsertTimesheetLinesParams) error {
	_, err := q.db.Exec(ctx, insertTimesheetLines,
		arg.TimesheetID,
		arg.EmployeeIds,
		arg.Dates,
		arg.Days,
	)
	return err
}

const isManager = `-- name: IsManager :one
WITH RECURSIVE up AS (
    SELECT e.manager_id AS id FROM hrm.employees e WHERE e.id = $2::bigint
    UNION
    SELECT e.manager_id FROM hrm.employees e JOIN up ON e.id = up.id
)
SELECT EXISTS (SELECT 1 FROM up JOIN hrm.employees m ON m.id = up.id WHERE m.user_id = $1::bigint)
`

type IsManagerParams struct {
	Actor    int64
	Employee int64
}

// Whether the user is linked to an employee above @employee on its manager chain.
func (q *Queries) IsManager(ctx context.Context, arg IsManagerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isManager, arg.Actor, arg.Employee)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const leaveBalanceDays = `-- name: LeaveBalanceDays :one
SELECT coalesce((SELECT days::text FROM hrm.leave_balances WHERE employee_id = $1 AND year = $2), '0')::text
`

type LeaveBalanceDaysParams struct {
	EmployeeID int64
	Year       int32
}

func (q *Queries) LeaveBalanceDays(ctx context.Context, arg LeaveBalanceDaysParams) (string, error) {
	row := q.db.QueryRow(ctx, leaveBalanceDays, arg.EmployeeID, arg.Year)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const leaveBalances = `-- name: LeaveBalances :many
SELECT year, days::text AS days FROM hrm.leave_balances WHERE employee_id = $1 ORDER BY year DESC
`

type LeaveBalancesRow struct {
	Year int32
	Days string
}

func (q *Queries) LeaveBalances(ctx context.Context, employeeID int64) ([]LeaveBalancesRow, error) {
	rows, err := q.db.Query(ctx, leaveBalances, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaveBalancesRow
	for rows.Next() {
		var i LeaveBalancesRow
		if err := rows.Scan(&i.Year, &i.Days); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const legalEntities = `-- name: LegalEntities :many
SELECT id FROM iam.org_units WHERE kind = 'company' ORDER BY id
`

func (q *Queries) LegalEntities(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, legalEntities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const legalParamsAt = `-- name: LegalParamsAt :many
SELECT DISTINCT ON (key) key, effective_from, value FROM hrm.legal_params
WHERE effective_from <= $1::date ORDER BY key, effective_from DESC
`

// Each key's version in force at @at.
func (q *Queries) LegalParamsAt(ctx context.Context, at pgtype.Date) ([]HrmLegalParam, error) {
	rows, err := q.db.Query(ctx, legalParamsAt, at)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmLegalParam
	for rows.Next() {
		var i HrmLegalParam
		if err := rows.Scan(&i.Key, &i.EffectiveFrom, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractTypes = `-- name: ListContractTypes :many
SELECT id, name, active, fixed_term FROM hrm.contract_types ORDER BY lower(name)
`

func (q *Queries) ListContractTypes(ctx context.Context) ([]HrmContractType, error) {
	rows, err := q.db.Query(ctx, listContractTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmContractType
	for rows.Next() {
		var i HrmContractType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Active,
			&i.FixedTerm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContracts = `-- name: ListContracts :many
SELECT c.id, d.number, d.status, c.parent_id, p.number AS parent_number, t.name AS contract_type_name,
       c.start_date, c.end_date, c.employee_id, e.code AS employee_code, e.full_name AS employee_name,
       count(*) OVER () AS total
FROM hrm.contracts c
JOIN record.documents d ON d.id = c.id
JOIN hrm.contract_types t ON t.id = c.contract_type_id
JOIN hrm.employees e ON e.id = c.employee_id
LEFT JOIN record.documents p ON p.id = c.parent_id
WHERE ($1::bool OR d.org_unit_id = ANY($2::bigint[]))
  AND ($3::text = '' OR d.status = $3)
  AND ($4::bigint IS NULL OR c.contract_type_id = $4)
  AND ($5::bigint IS NULL OR d.org_unit_id = $5)
  AND ($6::bigint IS NULL OR c.employee_id = $6)
  AND (NOT $7::bool OR (c.parent_id IS NULL AND d.status = 'posted'
       AND c.end_date BETWEEN $8::date AND $8::date + 30))
ORDER BY
    CASE WHEN $9::text = 'start_date' THEN c.start_date END,
    CASE WHEN $9 = '-start_date' THEN c.start_date END DESC,
    CASE WHEN $9 = 'end_date' THEN c.end_date END,
    CASE WHEN $9 = '-end_date' THEN c.end_date END DESC NULLS LAST,
    CASE WHEN $9 = 'number' THEN d.number END,
    CASE WHEN $9 = '-number' THEN d.number END DESC,
    c.id DESC
LIMIT $11 OFFSET $10
`

type ListContractsParams struct {
	AllUnits       bool
	Units          []int64
	Status         string
	ContractTypeID pgtype.Int8
	OrgUnitID      pgtype.Int8
	EmployeeID     pgtype.Int8
	Expiring       bool
	Today          pgtype.Date
	Sort           string
	Off            int32
	Lim            int32
}

type ListContractsRow struct {
	ID               int64
	Number           string
	Status           string
	ParentID         pgtype.Int8
	ParentNumber     pgtype.Text
	ContractTypeName string
	StartDate        pgtype.Date
	EndDate          pgtype.Date
	EmployeeID       int64
	EmployeeCode     string
	EmployeeName     string
	Total            int64
}

// Every contract and appendix in scope. Expiring: posted originals ending from @today to @today + 30 days.
func (q *Queries) ListContracts(ctx context.Context, arg ListContractsParams) ([]ListContractsRow, error) {
	rows, err := q.db.Query(ctx, listContracts,
		arg.AllUnits,
		arg.Units,
		arg.Status,
		arg.ContractTypeID,
		arg.OrgUnitID,
		arg.EmployeeID,
		arg.Expiring,
		arg.Today,
		arg.Sort,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContractsRow
	for rows.Next() {
		var i ListContractsRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Status,
			&i.ParentID,
			&i.ParentNumber,
			&i.ContractTypeName,
			&i.StartDate,
			&i.EndDate,
			&i.EmployeeID,
			&i.EmployeeCode,
			&i.EmployeeName,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDependents = `-- name: ListDependents :many
SELECT id, data FROM hrm.dependents WHERE employee_id = $1 ORDER BY id
`

type ListDependentsRow struct {
	ID   int64
	Data []byte
}

func (q *Queries) ListDependents(ctx context.Context, employeeID int64) ([]ListDependentsRow, error) {
	rows, err := q.db.Query(ctx, listDependents, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDependentsRow
	for rows.Next() {
		var i ListDependentsRow
		if err := rows.Scan(&i.ID, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeContracts = `-- name: ListEmployeeContracts :many
SELECT c.id, d.number, d.status, c.parent_id, t.name AS contract_type_name, c.start_date, c.end_date
FROM hrm.contracts c
JOIN record.documents d ON d.id = c.id
JOIN hrm.contract_types t ON t.id = c.contract_type_id
WHERE c.employee_id = $1 AND ($2::bool OR d.org_unit_id = ANY($3::bigint[]))
ORDER BY (SELECT o.start_date FROM hrm.contracts o WHERE o.id = coalesce(c.parent_id, c.id)) DESC,
         coalesce(c.parent_id, c.id) DESC, c.parent_id NULLS FIRST, c.start_date, c.id
`

type ListEmployeeContractsParams struct {
	EmployeeID int64
	AllUnits   bool
	Units      []int64
}

type ListEmployeeContractsRow struct {
	ID               int64
	Number           string
	Status           string
	ParentID         pgtype.Int8
	ContractTypeName string
	StartDate        pgtype.Date
	EndDate          pgtype.Date
}

// Originals each followed by their appendices; scope filter on the document's org unit.
func (q *Queries) ListEmployeeContracts(ctx context.Context, arg ListEmployeeContractsParams) ([]ListEmployeeContractsRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeContracts, arg.EmployeeID, arg.AllUnits, arg.Units)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmployeeContractsRow
	for rows.Next() {
		var i ListEmployeeContractsRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Status,
			&i.ParentID,
			&i.ContractTypeName,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployees = `-- name: ListEmployees :many
WITH RECURSIVE under (id) AS (
    SELECT $10::bigint WHERE $10::bigint IS NOT NULL
    UNION
    SELECT s.id FROM hrm.employees s JOIN under ON s.manager_id = under.id
)
SELECT e.id, e.code, e.full_name, e.org_unit_id, u.name AS org_unit_name, e.email, e.phone,
       e.hire_date, e.termination_date, count(*) OVER () AS total
FROM hrm.employees e JOIN iam.org_units u ON u.id = e.org_unit_id
WHERE ($1::bool OR e.org_unit_id = ANY($2::bigint[]))
  AND ($3::text = '' OR e.code ILIKE '%' || $3 || '%' OR e.full_name ILIKE '%' || $3 || '%')
  AND ($4::bigint IS NULL OR e.org_unit_id = $4)
  AND ($5::text = ''
       OR ($5 = 'active' AND (e.termination_date IS NULL OR e.termination_date >= $6::date))
       OR ($5 = 'terminated' AND e.termination_date < $6::date))
  AND e.id NOT IN (SELECT id FROM under)
ORDER BY
    CASE WHEN $7::text = 'code' THEN lower(e.code) END,
    CASE WHEN $7 = '-code' THEN lower(e.code) END DESC,
    CASE WHEN $7 = 'full_name' THEN e.full_name END,
    CASE WHEN $7 = '-full_name' THEN e.full_name END DESC,
    CASE WHEN $7 = 'hire_date' THEN e.hire_date END,
    CASE WHEN $7 = '-hire_date' THEN e.hire_date END DESC,
    e.id
LIMIT $9 OFFSET $8
`

type ListEmployeesParams struct {
	AllUnits  bool
	Units     []int64
	Q         string
	OrgUnitID pgtype.Int8
	Status    string
	Today     pgtype.Date
	Sort      string
	Off       int32
	Lim       int32
	ManagerOf pgtype.Int8
}

type ListEmployeesRow struct {
	ID              int64
	Code            string
	FullName        string
	OrgUnitID       int64
	OrgUnitName     string
	Email           pgtype.Text
	Phone           pgtype.Text
	HireDate        pgtype.Date
	TerminationDate pgtype.Date
	Total           int64
}

// Scope filter: @all_units or org_unit_id in @units. Status uses @today, in the tenant time zone.
// manager_of drops that employee and everyone under them, who cannot become their manager.
func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]ListEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listEmployees,
		arg.AllUnits,
		arg.Units,
		arg.Q,
		arg.OrgUnitID,
		arg.Status,
		arg.Today,
		arg.Sort,
		arg.Off,
		arg.Lim,
		arg.ManagerOf,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmployeesRow
	for rows.Next() {
		var i ListEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.FullName,
			&i.OrgUnitID,
			&i.OrgUnitName,
			&i.Email,
			&i.Phone,
			&i.HireDate,
			&i.TerminationDate,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaveRequests = `-- name: ListLeaveRequests :many
SELECT r.id, d.number, d.status, r.employee_id, e.code AS employee_code, e.full_name AS employee_name,
       t.name AS leave_type_name, r.start_date, r.end_date, r.days::text AS days, count(*) OVER () AS total
FROM hrm.leave_requests r
JOIN record.documents d ON d.id = r.id
JOIN hrm.employees e ON e.id = r.employee_id
JOIN hrm.leave_types t ON t.id = r.leave_type_id
WHERE ($1::bool OR d.org_unit_id = ANY($2::bigint[]) OR e.user_id = $3::bigint OR r.employee_id = ANY($4::bigint[]))
  AND ($5::text = '' OR d.status = $5)
  AND ($6::bigint IS NULL OR r.employee_id = $6)
  AND ($7::date IS NULL OR r.end_date >= $7)
  AND ($8::date IS NULL OR r.start_date <= $8)
ORDER BY
    CASE WHEN $9::text = 'start_date' THEN r.start_date END,
    CASE WHEN $9 = '-start_date' THEN r.start_date END DESC,
    CASE WHEN $9 = 'number' THEN d.number END,
    CASE WHEN $9 = '-number' THEN d.number END DESC,
    r.id DESC
LIMIT $11 OFFSET $10
`

type ListLeaveRequestsParams struct {
	AllUnits   bool
	Units      []int64
	Actor      int64
	Reports    []int64
	Status     string
	EmployeeID pgtype.Int8
	FromDate   pgtype.Date
	ToDate     pgtype.Date
	Sort       string
	Off        int32
	Lim        int32
}

type ListLeaveRequestsRow struct {
	ID            int64
	Number        string
	Status        string
	EmployeeID    int64
	EmployeeCode  string
	EmployeeName  string
	LeaveTypeName string
	StartDate     pgtype.Date
	EndDate       pgtype.Date
	Days          string
	Total         int64
}

// Visible: org unit in scope, the actor's own requests, or requests of the employees in @reports.
func (q *Queries) ListLeaveRequests(ctx context.Context, arg ListLeaveRequestsParams) ([]ListLeaveRequestsRow, error) {
	rows, err := q.db.Query(ctx, listLeaveRequests,
		arg.AllUnits,
		arg.Units,
		arg.Actor,
		arg.Reports,
		arg.Status,
		arg.EmployeeID,
		arg.FromDate,
		arg.ToDate,
		arg.Sort,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLeaveRequestsRow
	for rows.Next() {
		var i ListLeaveRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Status,
			&i.EmployeeID,
			&i.EmployeeCode,
			&i.EmployeeName,
			&i.LeaveTypeName,
			&i.StartDate,
			&i.EndDate,
			&i.Days,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaveTypes = `-- name: ListLeaveTypes :many
SELECT id, name, deducts_balance, active, paid FROM hrm.leave_types ORDER BY lower(name)
`

func (q *Queries) ListLeaveTypes(ctx context.Context) ([]HrmLeaveType, error) {
	rows, err := q.db.Query(ctx, listLeaveTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmLeaveType
	for rows.Next() {
		var i HrmLeaveType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DeductsBalance,
			&i.Active,
			&i.Paid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegalParams = `-- name: ListLegalParams :many
SELECT key, effective_from, value FROM hrm.legal_params ORDER BY key, effective_from
`

func (q *Queries) ListLegalParams(ctx context.Context) ([]HrmLegalParam, error) {
	rows, err := q.db.Query(ctx, listLegalParams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmLegalParam
	for rows.Next() {
		var i HrmLegalParam
		if err := rows.Scan(&i.Key, &i.EffectiveFrom, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOvertimeRequests = `-- name: ListOvertimeRequests :many
SELECT r.id, d.number, d.status, r.employee_id, e.code AS employee_code, e.full_name AS employee_name,
       r.date, r.day_kind, r.day_hours::text AS day_hours, r.night_hours::text AS night_hours, count(*) OVER () AS total
FROM hrm.overtime_requests r
JOIN record.documents d ON d.id = r.id
JOIN hrm.employees e ON e.id = r.employee_id
WHERE ($1::bool OR d.org_unit_id = ANY($2::bigint[]) OR e.user_id = $3::bigint OR r.employee_id = ANY($4::bigint[]))
  AND ($5::text = '' OR d.status = $5)
  AND ($6::bigint IS NULL OR r.employee_id = $6)
  AND ($7::date IS NULL OR r.date >= $7)
  AND ($8::date IS NULL OR r.date <= $8)
ORDER BY
    CASE WHEN $9::text = 'date' THEN r.date END,
    CASE WHEN $9 = '-date' THEN r.date END DESC,
    CASE WHEN $9 = 'number' THEN d.number END,
    CASE WHEN $9 = '-number' THEN d.number END DESC,
    r.id DESC
LIMIT $11 OFFSET $10
`

type ListOvertimeRequestsParams struct {
	AllUnits   bool
	Units      []int64
	Actor      int64
	Reports    []int64
	Status     string
	EmployeeID pgtype.Int8
	FromDate   pgtype.Date
	ToDate     pgtype.Date
	Sort       string
	Off        int32
	Lim        int32
}

type ListOvertimeRequestsRow struct {
	ID           int64
	Number       string
	Status       string
	EmployeeID   int64
	EmployeeCode string
	EmployeeName string
	Date         pgtype.Date
	DayKind      string
	DayHours     string
	NightHours   string
	Total        int64
}

// Visible as for leave requests.
func (q *Queries) ListOvertimeRequests(ctx context.Context, arg ListOvertimeRequestsParams) ([]ListOvertimeRequestsRow, error) {
	rows, err := q.db.Query(ctx, listOvertimeRequests,
		arg.AllUnits,
		arg.Units,
		arg.Actor,
		arg.Reports,
		arg.Status,
		arg.EmployeeID,
		arg.FromDate,
		arg.ToDate,
		arg.Sort,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOvertimeRequestsRow
	for rows.Next() {
		var i ListOvertimeRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Status,
			&i.EmployeeID,
			&i.EmployeeCode,
			&i.EmployeeName,
			&i.Date,
			&i.DayKind,
			&i.DayHours,
			&i.NightHours,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrolls = `-- name: ListPayrolls :many
SELECT p.id, d.number, d.status, d.legal_entity_id, u.name AS legal_entity_name, p.period_start, p.period_end,
       p.computed_at, count(*) OVER () AS total
FROM hrm.payrolls p
JOIN record.documents d ON d.id = p.id
JOIN iam.org_units u ON u.id = d.legal_entity_id
WHERE ($1::bool OR d.legal_entity_id = ANY($2::bigint[]))
  AND ($3::text = '' OR d.status = $3)
  AND ($4::bigint IS NULL OR d.legal_entity_id = $4)
  AND ($5::date IS NULL OR p.period_start = $5)
ORDER BY p.period_start DESC, u.name, p.id DESC
LIMIT $7 OFFSET $6
`

type ListPayrollsParams struct {
	AllUnits      bool
	Units         []int64
	Status        string
	LegalEntityID pgtype.Int8
	PeriodStart   pgtype.Date
	Off           int32
	Lim           int32
}

type ListPayrollsRow struct {
	ID              int64
	Number          string
	Status          string
	LegalEntityID   int64
	LegalEntityName string
	PeriodStart     pgtype.Date
	PeriodEnd       pgtype.Date
	ComputedAt      pgtype.Timestamptz
	Total           int64
}

func (q *Queries) ListPayrolls(ctx context.Context, arg ListPayrollsParams) ([]ListPayrollsRow, error) {
	rows, err := q.db.Query(ctx, listPayrolls,
		arg.AllUnits,
		arg.Units,
		arg.Status,
		arg.LegalEntityID,
		arg.PeriodStart,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPayrollsRow
	for rows.Next() {
		var i ListPayrollsRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Status,
			&i.LegalEntityID,
			&i.LegalEntityName,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.ComputedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimesheets = `-- name: ListTimesheets :many
SELECT t.id, d.number, d.status, t.org_unit_id, u.name AS org_unit_name, t.period_start, t.period_end, count(*) OVER () AS total
FROM hrm.timesheets t
JOIN record.documents d ON d.id = t.id
JOIN iam.org_units u ON u.id = t.org_unit_id
WHERE ($1::bool OR t.org_unit_id = ANY($2::bigint[]))
  AND ($3::text = '' OR d.status = $3)
  AND ($4::bigint IS NULL OR t.org_unit_id = $4)
  AND ($5::date IS NULL OR t.period_start = $5)
ORDER BY t.period_start DESC, u.name, t.id DESC
LIMIT $7 OFFSET $6
`

type ListTimesheetsParams struct {
	AllUnits    bool
	Units       []int64
	Status      string
	OrgUnitID   pgtype.Int8
	PeriodStart pgtype.Date
	Off         int32
	Lim         int32
}

type ListTimesheetsRow struct {
	ID          int64
	Number      string
	Status      string
	OrgUnitID   int64
	OrgUnitName string
	PeriodStart pgtype.Date
	PeriodEnd   pgtype.Date
	Total       int64
}

func (q *Queries) ListTimesheets(ctx context.Context, arg ListTimesheetsParams) ([]ListTimesheetsRow, error) {
	rows, err := q.db.Query(ctx, listTimesheets,
		arg.AllUnits,
		arg.Units,
		arg.Status,
		arg.OrgUnitID,
		arg.PeriodStart,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimesheetsRow
	for rows.Next() {
		var i ListTimesheetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Status,
			&i.OrgUnitID,
			&i.OrgUnitName,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEmployee = `-- name: LockEmployee :one
SELECT id, code, full_name, date_of_birth, gender, phone, email, address, org_unit_id, manager_id, user_id, hire_date, termination_date, national_id, social_insurance_no, tax_code, bank_account FROM hrm.employees WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockEmployee(ctx context.Context, id int64) (HrmEmployee, error) {
	row := q.db.QueryRow(ctx, lockEmployee, id)
	var i HrmEmployee
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.FullName,
		&i.DateOfBirth,
		&i.Gender,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.OrgUnitID,
		&i.ManagerID,
		&i.UserID,
		&i.HireDate,
		&i.TerminationDate,
		&i.NationalID,
		&i.SocialInsuranceNo,
		&i.TaxCode,
		&i.BankAccount,
	)
	return i, err
}

const lockManagerTree = `-- name: LockManagerTree :exec
SELECT pg_advisory_xact_lock(hashtext('hrm.manager_tree'))
`

// Serialises manager changes so two concurrent edits cannot close a cycle.
func (q *Queries) LockManagerTree(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockManagerTree)
	return err
}

const lockPayrollLock = `-- name: LockPayrollLock :exec
SELECT legal_entity_id FROM hrm.payroll_locks WHERE legal_entity_id = $1 FOR UPDATE
`

func (q *Queries) LockPayrollLock(ctx context.Context, legalEntityID int64) error {
	_, err := q.db.Exec(ctx, lockPayrollLock, legalEntityID)
	return err
}

const managerChain = `-- name: ManagerChain :many
WITH RECURSIVE chain (employee_id, next_id) AS (
    SELECT s.id, s.manager_id FROM hrm.employees s WHERE s.id = $1::bigint
    UNION
    SELECT e.id, e.manager_id FROM hrm.employees e JOIN chain ON e.id = chain.next_id
)
SELECT employee_id FROM chain
`

// The employee and everyone above it; UNION stops on a cycle.
func (q *Queries) ManagerChain(ctx context.Context, start int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, managerChain, start)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var employee_id int64
		if err := rows.Scan(&employee_id); err != nil {
			return nil, err
		}
		items = append(items, employee_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const managerUser = `-- name: ManagerUser :one
WITH RECURSIVE chain (id, depth) AS (
    SELECT e.manager_id, 1 FROM hrm.employees e WHERE e.id = $2::bigint
    UNION ALL
    SELECT e.manager_id, chain.depth + 1 FROM hrm.employees e JOIN chain ON e.id = chain.id WHERE chain.depth < $1::int
)
SELECT m.user_id FROM chain JOIN hrm.employees m ON m.id = chain.id WHERE chain.depth = $1::int
`

type ManagerUserParams struct {
	Level    int32
	Employee int64
}

// The account of the manager @level steps above @employee.
func (q *Queries) ManagerUser(ctx context.Context, arg ManagerUserParams) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, managerUser, arg.Level, arg.Employee)
	var user_id pgtype.Int8
	err := row.Scan(&user_id)
	return user_id, err
}

const orgUnitNames = `-- name: OrgUnitNames :many
SELECT id, name FROM iam.org_units WHERE id = ANY($1::bigint[]) ORDER BY name
`

type OrgUnitNamesRow struct {
	ID   int64
	Name string
}

func (q *Queries) OrgUnitNames(ctx context.Context, ids []int64) ([]OrgUnitNamesRow, error) {
	rows, err := q.db.Query(ctx, orgUnitNames, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgUnitNamesRow
	for rows.Next() {
		var i OrgUnitNamesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const payrollAdjustments = `-- name: PayrollAdjustments :many
SELECT a.id, a.employee_id, a.source_period, a.data, e.code, e.full_name
FROM hrm.payroll_adjustments a JOIN hrm.employees e ON e.id = a.employee_id
WHERE a.payroll_id = $1 ORDER BY a.id
`

type PayrollAdjustmentsRow struct {
	ID           int64
	EmployeeID   int64
	SourcePeriod pgtype.Date
	Data         []byte
	Code         string
	FullName     string
}

func (q *Queries) PayrollAdjustments(ctx context.Context, payrollID int64) ([]PayrollAdjustmentsRow, error) {
	rows, err := q.db.Query(ctx, payrollAdjustments, payrollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayrollAdjustmentsRow
	for rows.Next() {
		var i PayrollAdjustmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.SourcePeriod,
			&i.Data,
			&i.Code,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const payrollContracts = `-- name: PayrollContracts :many
SELECT c.id, c.employee_id, c.parent_id, c.start_date, coalesce(p.end_date, c.end_date) AS end_date, c.terms
FROM hrm.contracts c JOIN record.documents d ON d.id = c.id LEFT JOIN hrm.contracts p ON p.id = c.parent_id
WHERE d.status = 'posted' AND d.legal_entity_id = $1 AND c.employee_id = ANY($2::bigint[]) AND c.start_date <= $3::date
  AND (coalesce(p.end_date, c.end_date) IS NULL OR coalesce(p.end_date, c.end_date) >= $4::date)
ORDER BY c.employee_id, c.start_date, c.id
`

type PayrollContractsParams struct {
	LegalEntityID int64
	Ids           []int64
	PeriodEnd     pgtype.Date
	PrevStart     pgtype.Date
}

type PayrollContractsRow struct {
	ID         int64
	EmployeeID int64
	ParentID   pgtype.Int8
	StartDate  pgtype.Date
	EndDate    pgtype.Date
	Terms      []byte
}

// Posted contracts and appendices with the legal entity of the employees that may be in force
// from @prev_start to @period_end; an appendix runs to its original's end.
func (q *Queries) PayrollContracts(ctx context.Context, arg PayrollContractsParams) ([]PayrollContractsRow, error) {
	rows, err := q.db.Query(ctx, payrollContracts,
		arg.LegalEntityID,
		arg.Ids,
		arg.PeriodEnd,
		arg.PrevStart,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayrollContractsRow
	for rows.Next() {
		var i PayrollContractsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.ParentID,
			&i.StartDate,
			&i.EndDate,
			&i.Terms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const payrollDependents = `-- name: PayrollDependents :many
SELECT employee_id, data FROM hrm.dependents WHERE employee_id = ANY($1::bigint[]) ORDER BY employee_id, id
`

type PayrollDependentsRow struct {
	EmployeeID int64
	Data       []byte
}

func (q *Queries) PayrollDependents(ctx context.Context, ids []int64) ([]PayrollDependentsRow, error) {
	rows, err := q.db.Query(ctx, payrollDependents, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayrollDependentsRow
	for rows.Next() {
		var i PayrollDependentsRow
		if err := rows.Scan(&i.EmployeeID, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const payrollEmployees = `-- name: PayrollEmployees :many
SELECT e.id, e.code, e.full_name, e.org_unit_id, e.hire_date, e.termination_date
FROM hrm.employees e
WHERE (e.hire_date <= $1::date AND (e.termination_date IS NULL OR e.termination_date >= $2::date)
       AND EXISTS (SELECT 1 FROM hrm.contracts c JOIN record.documents d ON d.id = c.id
                   WHERE c.employee_id = e.id AND c.parent_id IS NULL AND d.status = 'posted' AND d.legal_entity_id = $3
                     AND c.start_date <= $1 AND (c.end_date IS NULL OR c.end_date >= $2)))
   OR e.id IN (SELECT a.employee_id FROM hrm.payroll_adjustments a WHERE a.payroll_id = $4)
ORDER BY lower(e.code)
`

type PayrollEmployeesParams struct {
	PeriodEnd     pgtype.Date
	PeriodStart   pgtype.Date
	LegalEntityID int64
	PayrollID     int64
}

type PayrollEmployeesRow struct {
	ID              int64
	Code            string
	FullName        string
	OrgUnitID       int64
	HireDate        pgtype.Date
	TerminationDate pgtype.Date
}

// Employees of the period: a posted original contract with the legal entity overlapping it,
// employed during it; and anyone with an adjustment on the payroll.
func (q *Queries) PayrollEmployees(ctx context.Context, arg PayrollEmployeesParams) ([]PayrollEmployeesRow, error) {
	rows, err := q.db.Query(ctx, payrollEmployees,
		arg.PeriodEnd,
		arg.PeriodStart,
		arg.LegalEntityID,
		arg.PayrollID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayrollEmployeesRow
	for rows.Next() {
		var i PayrollEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.FullName,
			&i.OrgUnitID,
			&i.HireDate,
			&i.TerminationDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const payrollLeaveBalances = `-- name: PayrollLeaveBalances :many
SELECT employee_id, days::text AS days FROM hrm.leave_balances WHERE employee_id = ANY($1::bigint[]) AND year = $2
`

type PayrollLeaveBalancesParams struct {
	Ids  []int64
	Year int32
}

type PayrollLeaveBalancesRow struct {
	EmployeeID int64
	Days       string
}

func (q *Queries) PayrollLeaveBalances(ctx context.Context, arg PayrollLeaveBalancesParams) ([]PayrollLeaveBalancesRow, error) {
	rows, err := q.db.Query(ctx, payrollLeaveBalances, arg.Ids, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayrollLeaveBalancesRow
	for rows.Next() {
		var i PayrollLeaveBalancesRow
		if err := rows.Scan(&i.EmployeeID, &i.Days); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const payrollLeaves = `-- name: PayrollLeaves :many
SELECT r.employee_id, r.start_date, r.end_date, r.days::text AS days, t.paid
FROM hrm.leave_requests r JOIN hrm.leave_types t ON t.id = r.leave_type_id JOIN record.documents d ON d.id = r.id
WHERE d.status = 'posted' AND r.employee_id = ANY($1::bigint[]) AND r.start_date <= $2::date AND r.end_date >= $3::date
ORDER BY r.employee_id, r.start_date, r.id
`

type PayrollLeavesParams struct {
	Ids         []int64
	PeriodEnd   pgtype.Date
	PeriodStart pgtype.Date
}

type PayrollLeavesRow struct {
	EmployeeID int64
	StartDate  pgtype.Date
	EndDate    pgtype.Date
	Days       string
	Paid       bool
}

func (q *Queries) PayrollLeaves(ctx context.Context, arg PayrollLeavesParams) ([]PayrollLeavesRow, error) {
	rows, err := q.db.Query(ctx, payrollLeaves, arg.Ids, arg.PeriodEnd, arg.PeriodStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayrollLeavesRow
	for rows.Next() {
		var i PayrollLeavesRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.StartDate,
			&i.EndDate,
			&i.Days,
			&i.Paid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const payrollLines = `-- name: PayrollLines :many
SELECT l.employee_id, l.org_unit_id, l.data, e.code, e.full_name
FROM hrm.payroll_lines l JOIN hrm.employees e ON e.id = l.employee_id
WHERE l.payroll_id = $1 ORDER BY lower(e.code)
`

type PayrollLinesRow struct {
	EmployeeID int64
	OrgUnitID  int64
	Data       []byte
	Code       string
	FullName   string
}

func (q *Queries) PayrollLines(ctx context.Context, payrollID int64) ([]PayrollLinesRow, error) {
	rows, err := q.db.Query(ctx, payrollLines, payrollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayrollLinesRow
	for rows.Next() {
		var i PayrollLinesRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.OrgUnitID,
			&i.Data,
			&i.Code,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const payrollOvertime = `-- name: PayrollOvertime :many
SELECT o.employee_id, o.date, o.day_kind, o.day_hours::text AS day_hours, o.night_hours::text AS night_hours
FROM hrm.overtime_requests o JOIN record.documents d ON d.id = o.id
WHERE d.status = 'posted' AND o.employee_id = ANY($1::bigint[]) AND o.date BETWEEN $2::date AND $3::date
ORDER BY o.employee_id, o.date, o.id
`

type PayrollOvertimeParams struct {
	Ids       []int64
	YearStart pgtype.Date
	PeriodEnd pgtype.Date
}

type PayrollOvertimeRow struct {
	EmployeeID int64
	Date       pgtype.Date
	DayKind    string
	DayHours   string
	NightHours string
}

func (q *Queries) PayrollOvertime(ctx context.Context, arg PayrollOvertimeParams) ([]PayrollOvertimeRow, error) {
	rows, err := q.db.Query(ctx, payrollOvertime, arg.Ids, arg.YearStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayrollOvertimeRow
	for rows.Next() {
		var i PayrollOvertimeRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.Date,
			&i.DayKind,
			&i.DayHours,
			&i.NightHours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const payrollSourceDocs = `-- name: PayrollSourceDocs :many
SELECT d.doc_type, d.id, d.version FROM record.documents d
WHERE d.legal_entity_id = $1 AND d.status = 'posted' AND (
       (d.doc_type = 'hrm.contract' AND EXISTS (
            SELECT 1 FROM hrm.contracts c LEFT JOIN hrm.contracts p ON p.id = c.parent_id
            WHERE c.id = d.id AND c.start_date <= $2::date
              AND (coalesce(p.end_date, c.end_date) IS NULL OR coalesce(p.end_date, c.end_date) >= $3::date)))
    OR (d.doc_type = 'hrm.timesheet' AND EXISTS (SELECT 1 FROM hrm.timesheets t WHERE t.id = d.id AND t.period_start = $4::date))
    OR (d.doc_type = 'hrm.leave_request' AND EXISTS (
            SELECT 1 FROM hrm.leave_requests r WHERE r.id = d.id AND r.start_date <= $2 AND r.end_date >= $4))
    OR (d.doc_type = 'hrm.overtime_request' AND EXISTS (
            SELECT 1 FROM hrm.overtime_requests o WHERE o.id = d.id AND o.date BETWEEN $5::date AND $2)))
ORDER BY d.doc_type, d.id
`

type PayrollSourceDocsParams struct {
	LegalEntityID int64
	PeriodEnd     pgtype.Date
	PrevStart     pgtype.Date
	PeriodStart   pgtype.Date
	YearStart     pgtype.Date
}

type PayrollSourceDocsRow struct {
	DocType string
	ID      int64
	Version int32
}

// Posted documents of the legal entity a payroll of [@period_start, @period_end] reads: contracts
// and appendices in force over it, its timesheets and leave, and overtime since @year_start.
func (q *Queries) PayrollSourceDocs(ctx context.Context, arg PayrollSourceDocsParams) ([]PayrollSourceDocsRow, error) {
	rows, err := q.db.Query(ctx, payrollSourceDocs,
		arg.LegalEntityID,
		arg.PeriodEnd,
		arg.PrevStart,
		arg.PeriodStart,
		arg.YearStart,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayrollSourceDocsRow
	for rows.Next() {
		var i PayrollSourceDocsRow
		if err := rows.Scan(&i.DocType, &i.ID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const payrollWorkedDays = `-- name: PayrollWorkedDays :many
SELECT l.employee_id, l.date, l.days::text AS days
FROM hrm.timesheet_lines l JOIN hrm.timesheets t ON t.id = l.timesheet_id JOIN record.documents d ON d.id = t.id
WHERE d.status = 'posted' AND t.period_start = $1 AND l.employee_id = ANY($2::bigint[])
ORDER BY l.employee_id, l.date
`

type PayrollWorkedDaysParams struct {
	PeriodStart pgtype.Date
	Ids         []int64
}

type PayrollWorkedDaysRow struct {
	EmployeeID int64
	Date       pgtype.Date
	Days       string
}

func (q *Queries) PayrollWorkedDays(ctx context.Context, arg PayrollWorkedDaysParams) ([]PayrollWorkedDaysRow, error) {
	rows, err := q.db.Query(ctx, payrollWorkedDays, arg.PeriodStart, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayrollWorkedDaysRow
	for rows.Next() {
		var i PayrollWorkedDaysRow
		if err := rows.Scan(&i.EmployeeID, &i.Date, &i.Days); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postedPayroll = `-- name: PostedPayroll :one
SELECT posted_payroll_id FROM hrm.payroll_periods WHERE legal_entity_id = $1 AND period_start = $2
`

type PostedPayrollParams struct {
	LegalEntityID int64
	PeriodStart   pgtype.Date
}

func (q *Queries) PostedPayroll(ctx context.Context, arg PostedPayrollParams) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, postedPayroll, arg.LegalEntityID, arg.PeriodStart)
	var posted_payroll_id pgtype.Int8
	err := row.Scan(&posted_payroll_id)
	return posted_payroll_id, err
}

const postedTimesheetUnits = `-- name: PostedTimesheetUnits :many
SELECT t.org_unit_id FROM hrm.timesheets t JOIN record.documents d ON d.id = t.id
WHERE d.status = 'posted' AND t.period_start = $1
`

func (q *Queries) PostedTimesheetUnits(ctx context.Context, periodStart pgtype.Date) ([]int64, error) {
	rows, err := q.db.Query(ctx, postedTimesheetUnits, periodStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var org_unit_id int64
		if err := rows.Scan(&org_unit_id); err != nil {
			return nil, err
		}
		items = append(items, org_unit_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const printLegalEntity = `-- name: PrintLegalEntity :one
SELECT coalesce(legal_name, name)::text AS name, tax_code, address FROM iam.org_units WHERE id = $1
`

type PrintLegalEntityRow struct {
	Name    string
	TaxCode pgtype.Text
	Address pgtype.Text
}

func (q *Queries) PrintLegalEntity(ctx context.Context, id int64) (PrintLegalEntityRow, error) {
	row := q.db.QueryRow(ctx, printLegalEntity, id)
	var i PrintLegalEntityRow
	err := row.Scan(&i.Name, &i.TaxCode, &i.Address)
	return i, err
}

const reports = `-- name: Reports :many
WITH RECURSIVE down AS (
    SELECT e.id FROM hrm.employees e JOIN hrm.employees me ON e.manager_id = me.id WHERE me.user_id = $1::bigint
    UNION
    SELECT e.id FROM hrm.employees e JOIN down ON e.manager_id = down.id
)
SELECT down.id FROM down
`

// Employees below the actor's own employee record, at any depth.
func (q *Queries) Reports(ctx context.Context, actor int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, reports, actor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveHoliday = `-- name: SaveHoliday :exec
INSERT INTO hrm.holidays (legal_entity_id, date, name) VALUES ($1, $2, $3)
ON CONFLICT (legal_entity_id, date) DO UPDATE SET name = excluded.name
`

type SaveHolidayParams struct {
	LegalEntityID int64
	Date          pgtype.Date
	Name          string
}

func (q *Queries) SaveHoliday(ctx context.Context, arg SaveHolidayParams) error {
	_, err := q.db.Exec(ctx, saveHoliday, arg.LegalEntityID, arg.Date, arg.Name)
	return err
}

const saveLegalParam = `-- name: SaveLegalParam :exec
INSERT INTO hrm.legal_params (key, effective_from, value) VALUES ($1, $2, $3)
ON CONFLICT (key, effective_from) DO UPDATE SET value = excluded.value
`

type SaveLegalParamParams struct {
	Key           string
	EffectiveFrom pgtype.Date
	Value         string
}

func (q *Queries) SaveLegalParam(ctx context.Context, arg SaveLegalParamParams) error {
	_, err := q.db.Exec(ctx, saveLegalParam, arg.Key, arg.EffectiveFrom, arg.Value)
	return err
}

const savePayrollResult = `-- name: SavePayrollResult :exec
UPDATE hrm.payrolls SET computed_at = now(), inputs_hash = $1 WHERE id = $2
`

type SavePayrollResultParams struct {
	InputsHash []byte
	ID         int64
}

func (q *Queries) SavePayrollResult(ctx context.Context, arg SavePayrollResultParams) error {
	_, err := q.db.Exec(ctx, savePayrollResult, arg.InputsHash, arg.ID)
	return err
}

const saveWorkWeek = `-- name: SaveWorkWeek :exec
INSERT INTO hrm.work_weeks (legal_entity_id, effective_from, off_days) VALUES ($1, $2, $3)
ON CONFLICT (legal_entity_id, effective_from) DO UPDATE SET off_days = excluded.off_days
`

type SaveWorkWeekParams struct {
	LegalEntityID int64
	EffectiveFrom pgtype.Date
	OffDays       []int16
}

func (q *Queries) SaveWorkWeek(ctx context.Context, arg SaveWorkWeekParams) error {
	_, err := q.db.Exec(ctx, saveWorkWeek, arg.LegalEntityID, arg.EffectiveFrom, arg.OffDays)
	return err
}

const setLeaveDeducted = `-- name: SetLeaveDeducted :exec
UPDATE hrm.leave_requests SET deducted = CAST($1::text AS numeric) WHERE id = $2
`

type SetLeaveDeductedParams struct {
	Deducted string
	ID       int64
}

func (q *Queries) SetLeaveDeducted(ctx context.Context, arg SetLeaveDeductedParams) error {
	_, err := q.db.Exec(ctx, setLeaveDeducted, arg.Deducted, arg.ID)
	return err
}

const setPostedPayroll = `-- name: SetPostedPayroll :exec
UPDATE hrm.payroll_periods SET posted_payroll_id = $3 WHERE legal_entity_id = $1 AND period_start = $2
`

type SetPostedPayrollParams struct {
	LegalEntityID   int64
	PeriodStart     pgtype.Date
	PostedPayrollID pgtype.Int8
}

func (q *Queries) SetPostedPayroll(ctx context.Context, arg SetPostedPayrollParams) error {
	_, err := q.db.Exec(ctx, setPostedPayroll, arg.LegalEntityID, arg.PeriodStart, arg.PostedPayrollID)
	return err
}

const sharePayrollLock = `-- name: SharePayrollLock :exec
SELECT legal_entity_id FROM hrm.payroll_locks WHERE legal_entity_id = $1 FOR SHARE
`

func (q *Queries) SharePayrollLock(ctx context.Context, legalEntityID int64) error {
	_, err := q.db.Exec(ctx, sharePayrollLock, legalEntityID)
	return err
}

const timesheetEmployees = `-- name: TimesheetEmployees :many
SELECT e.id, e.code, e.full_name, e.hire_date, e.termination_date
FROM hrm.employees e
WHERE (e.org_unit_id = $1 AND e.hire_date <= $2::date
       AND (e.termination_date IS NULL OR e.termination_date >= $3::date))
   OR e.id IN (SELECT l.employee_id FROM hrm.timesheet_lines l WHERE l.timesheet_id = $4)
ORDER BY lower(e.code)
`

type TimesheetEmployeesParams struct {
	OrgUnitID   int64
	PeriodEnd   pgtype.Date
	PeriodStart pgtype.Date
	TimesheetID int64
}

type TimesheetEmployeesRow struct {
	ID              int64
	Code            string
	FullName        string
	HireDate        pgtype.Date
	TerminationDate pgtype.Date
}

// The grid: employees of exactly the unit employed during the period, and anyone with lines.
func (q *Queries) TimesheetEmployees(ctx context.Context, arg TimesheetEmployeesParams) ([]TimesheetEmployeesRow, error) {
	rows, err := q.db.Query(ctx, timesheetEmployees,
		arg.OrgUnitID,
		arg.PeriodEnd,
		arg.PeriodStart,
		arg.TimesheetID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimesheetEmployeesRow
	for rows.Next() {
		var i TimesheetEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.FullName,
			&i.HireDate,
			&i.TerminationDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const timesheetLines = `-- name: TimesheetLines :many
SELECT employee_id, date, days::text AS days FROM hrm.timesheet_lines WHERE timesheet_id = $1 ORDER BY employee_id, date
`

type TimesheetLinesRow struct {
	EmployeeID int64
	Date       pgtype.Date
	Days       string
}

func (q *Queries) TimesheetLines(ctx context.Context, timesheetID int64) ([]TimesheetLinesRow, error) {
	rows, err := q.db.Query(ctx, timesheetLines, timesheetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimesheetLinesRow
	for rows.Next() {
		var i TimesheetLinesRow
		if err := rows.Scan(&i.EmployeeID, &i.Date, &i.Days); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContract = `-- name: UpdateContract :exec
UPDATE hrm.contracts SET contract_type_id = $2, start_date = $3, end_date = $4, terms = $5 WHERE id = $1
`

type UpdateContractParams struct {
	ID             int64
	ContractTypeID int64
	StartDate      pgtype.Date
	EndDate        pgtype.Date
	Terms          []byte
}

func (q *Queries) UpdateContract(ctx context.Context, arg UpdateContractParams) error {
	_, err := q.db.Exec(ctx, updateContract,
		arg.ID,
		arg.ContractTypeID,
		arg.StartDate,
		arg.EndDate,
		arg.Terms,
	)
	return err
}

const updateContractType = `-- name: UpdateContractType :execrows
UPDATE hrm.contract_types SET name = $2, fixed_term = $3, active = $4 WHERE id = $1
`

type UpdateContractTypeParams struct {
	ID        int64
	Name      string
	FixedTerm bool
	Active    bool
}

func (q *Queries) UpdateContractType(ctx context.Context, arg UpdateContractTypeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateContractType,
		arg.ID,
		arg.Name,
		arg.FixedTerm,
		arg.Active,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDependent = `-- name: UpdateDependent :exec
UPDATE hrm.dependents SET data = $3 WHERE id = $1 AND employee_id = $2
`

type UpdateDependentParams struct {
	ID         int64
	EmployeeID int64
	Data       []byte
}

func (q *Queries) UpdateDependent(ctx context.Context, arg UpdateDependentParams) error {
	_, err := q.db.Exec(ctx, updateDependent, arg.ID, arg.EmployeeID, arg.Data)
	return err
}

const updateEmployee = `-- name: UpdateEmployee :exec
UPDATE hrm.employees SET code = $2, full_name = $3, date_of_birth = $4, gender = $5, phone = $6, email = $7,
    address = $8, org_unit_id = $9, manager_id = $10, user_id = $11, hire_date = $12, termination_date = $13,
    national_id = $14, social_insurance_no = $15, tax_code = $16, bank_account = $17
WHERE id = $1
`

type UpdateEmployeeParams struct {
	ID                int64
	Code              string
	FullName          string
	DateOfBirth       pgtype.Date
	Gender            pgtype.Text
	Phone             pgtype.Text
	Email             pgtype.Text
	Address           pgtype.Text
	OrgUnitID         int64
	ManagerID         pgtype.Int8
	UserID            pgtype.Int8
	HireDate          pgtype.Date
	TerminationDate   pgtype.Date
	NationalID        []byte
	SocialInsuranceNo []byte
	TaxCode           []byte
	BankAccount       []byte
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) error {
	_, err := q.db.Exec(ctx, updateEmployee,
		arg.ID,
		arg.Code,
		arg.FullName,
		arg.DateOfBirth,
		arg.Gender,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.OrgUnitID,
		arg.ManagerID,
		arg.UserID,
		arg.HireDate,
		arg.TerminationDate,
		arg.NationalID,
		arg.SocialInsuranceNo,
		arg.TaxCode,
		arg.BankAccount,
	)
	return err
}

const updateLeaveRequest = `-- name: UpdateLeaveRequest :exec
UPDATE hrm.leave_requests SET leave_type_id = $1, start_date = $2, end_date = $3,
    days = CAST($4::text AS numeric), reason = $5
WHERE id = $6
`

type UpdateLeaveRequestParams struct {
	LeaveTypeID int64
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	Days        string
	Reason      pgtype.Text
	ID          int64
}

func (q *Queries) UpdateLeaveRequest(ctx context.Context, arg UpdateLeaveRequestParams) error {
	_, err := q.db.Exec(ctx, updateLeaveRequest,
		arg.LeaveTypeID,
		arg.StartDate,
		arg.EndDate,
		arg.Days,
		arg.Reason,
		arg.ID,
	)
	return err
}

const updateLeaveType = `-- name: UpdateLeaveType :execrows
UPDATE hrm.leave_types SET name = $2, deducts_balance = $3, paid = $4, active = $5 WHERE id = $1
`

type UpdateLeaveTypeParams struct {
	ID             int64
	Name           string
	DeductsBalance bool
	Paid           bool
	Active         bool
}

func (q *Queries) UpdateLeaveType(ctx context.Context, arg UpdateLeaveTypeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLeaveType,
		arg.ID,
		arg.Name,
		arg.DeductsBalance,
		arg.Paid,
		arg.Active,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOvertimeRequest = `-- name: UpdateOvertimeRequest :exec
UPDATE hrm.overtime_requests SET date = $1, day_kind = $2, day_hours = CAST($3::text AS numeric),
    night_hours = CAST($4::text AS numeric), reason = $5
WHERE id = $6
`

type UpdateOvertimeRequestParams struct {
	Date       pgtype.Date
	DayKind    string
	DayHours   string
	NightHours string
	Reason     pgtype.Text
	ID         int64
}

func (q *Queries) UpdateOvertimeRequest(ctx context.Context, arg UpdateOvertimeRequestParams) error {
	_, err := q.db.Exec(ctx, updateOvertimeRequest,
		arg.Date,
		arg.DayKind,
		arg.DayHours,
		arg.NightHours,
		arg.Reason,
		arg.ID,
	)
	return err
}

const updateTimesheetPeriod = `-- name: UpdateTimesheetPeriod :exec
UPDATE hrm.timesheets SET period_start = $2, period_end = $3 WHERE id = $1
`

type UpdateTimesheetPeriodParams struct {
	ID          int64
	PeriodStart pgtype.Date
	PeriodEnd   pgtype.Date
}

func (q *Queries) UpdateTimesheetPeriod(ctx context.Context, arg UpdateTimesheetPeriodParams) error {
	_, err := q.db.Exec(ctx, updateTimesheetPeriod, arg.ID, arg.PeriodStart, arg.PeriodEnd)
	return err
}

const workWeeks = `-- name: WorkWeeks :many
SELECT effective_from, off_days FROM hrm.work_weeks WHERE legal_entity_id = $1 ORDER BY effective_from
`

type WorkWeeksRow struct {
	EffectiveFrom pgtype.Date
	OffDays       []int16
}

func (q *Queries) WorkWeeks(ctx context.Context, legalEntityID int64) ([]WorkWeeksRow, error) {
	rows, err := q.db.Query(ctx, workWeeks, legalEntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkWeeksRow
	for rows.Next() {
		var i WorkWeeksRow
		if err := rows.Scan(&i.EffectiveFrom, &i.OffDays); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
