// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO discussion.comments (doc_type, doc_id, author_id, body) VALUES ($1, $2, $3, $4) RETURNING id
`

type CreateCommentParams struct {
	DocType  string
	DocID    int64
	AuthorID int64
	Body     string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (int64, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.DocType,
		arg.DocID,
		arg.AuthorID,
		arg.Body,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteRecordComments = `-- name: DeleteRecordComments :exec
DELETE FROM discussion.comments WHERE doc_type = $1 AND doc_id = $2
`

type DeleteRecordCommentsParams struct {
	DocType string
	DocID   int64
}

func (q *Queries) DeleteRecordComments(ctx context.Context, arg DeleteRecordCommentsParams) error {
	_, err := q.db.Exec(ctx, deleteRecordComments, arg.DocType, arg.DocID)
	return err
}

const listComments = `-- name: ListComments :many
SELECT c.id, c.body, c.created_at, u.name AS author_name
FROM discussion.comments c JOIN iam.users u ON u.id = c.author_id
WHERE c.doc_type = $1 AND c.doc_id = $2
ORDER BY c.id
`

type ListCommentsParams struct {
	DocType string
	DocID   int64
}

type ListCommentsRow struct {
	ID         int64
	Body       string
	CreatedAt  pgtype.Timestamptz
	AuthorName string
}

func (q *Queries) ListComments(ctx context.Context, arg ListCommentsParams) ([]ListCommentsRow, error) {
	rows, err := q.db.Query(ctx, listComments, arg.DocType, arg.DocID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsRow
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const users = `-- name: Users :many
SELECT id, login, name FROM iam.users ORDER BY name, login
`

type UsersRow struct {
	ID    int64
	Login string
	Name  string
}

func (q *Queries) Users(ctx context.Context) ([]UsersRow, error) {
	rows, err := q.db.Query(ctx, users)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersRow
	for rows.Next() {
		var i UsersRow
		if err := rows.Scan(&i.ID, &i.Login, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usersByLogin = `-- name: UsersByLogin :many
SELECT id FROM iam.users WHERE lower(login) = ANY($1::text[])
`

func (q *Queries) UsersByLogin(ctx context.Context, logins []string) ([]int64, error) {
	rows, err := q.db.Query(ctx, usersByLogin, logins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
