// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApprovalInstance struct {
	ID              int64
	DocType         string
	DocID           int64
	Version         int32
	SubmittedBy     int64
	SubmittedAt     pgtype.Timestamptz
	Status          string
	CurrentStep     int32
	MaxLevels       int32
	FallbackProduct string
	FallbackRole    string
}

type ApprovalInstanceStep struct {
	InstanceID int64
	Position   int32
	Approver   []byte
	Approvers  []int64
	Fallback   bool
	DecidedBy  pgtype.Int8
	Decision   pgtype.Text
	Reason     pgtype.Text
	DecidedAt  pgtype.Timestamptz
}

type ApprovalRule struct {
	DocType         string
	Steps           []byte
	MaxLevels       int32
	FallbackProduct string
	FallbackRole    string
}
