// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeInstance = `-- name: CloseInstance :exec
UPDATE approval.instances SET status = $2 WHERE id = $1 AND status = 'open'
`

type CloseInstanceParams struct {
	ID     int64
	Status string
}

func (q *Queries) CloseInstance(ctx context.Context, arg CloseInstanceParams) error {
	_, err := q.db.Exec(ctx, closeInstance, arg.ID, arg.Status)
	return err
}

const decide = `-- name: Decide :exec
UPDATE approval.instance_steps SET decided_by = $1, decision = $2, reason = $3, decided_at = now()
WHERE instance_id = $4 AND position = $5
`

type DecideParams struct {
	DecidedBy  pgtype.Int8
	Decision   pgtype.Text
	Reason     pgtype.Text
	InstanceID int64
	Position   int32
}

func (q *Queries) Decide(ctx context.Context, arg DecideParams) error {
	_, err := q.db.Exec(ctx, decide,
		arg.DecidedBy,
		arg.Decision,
		arg.Reason,
		arg.InstanceID,
		arg.Position,
	)
	return err
}

const deleteRule = `-- name: DeleteRule :exec
DELETE FROM approval.rules WHERE doc_type = $1
`

func (q *Queries) DeleteRule(ctx context.Context, docType string) error {
	_, err := q.db.Exec(ctx, deleteRule, docType)
	return err
}

const getInstance = `-- name: GetInstance :one
SELECT id, doc_type, doc_id, version, submitted_by, submitted_at, status, current_step, max_levels, fallback_product, fallback_role FROM approval.instances WHERE id = $1
`

func (q *Queries) GetInstance(ctx context.Context, id int64) (ApprovalInstance, error) {
	row := q.db.QueryRow(ctx, getInstance, id)
	var i ApprovalInstance
	err := row.Scan(
		&i.ID,
		&i.DocType,
		&i.DocID,
		&i.Version,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.Status,
		&i.CurrentStep,
		&i.MaxLevels,
		&i.FallbackProduct,
		&i.FallbackRole,
	)
	return i, err
}

const getRule = `-- name: GetRule :one
SELECT doc_type, steps, max_levels, fallback_product, fallback_role FROM approval.rules WHERE doc_type = $1
`

func (q *Queries) GetRule(ctx context.Context, docType string) (ApprovalRule, error) {
	row := q.db.QueryRow(ctx, getRule, docType)
	var i ApprovalRule
	err := row.Scan(
		&i.DocType,
		&i.Steps,
		&i.MaxLevels,
		&i.FallbackProduct,
		&i.FallbackRole,
	)
	return i, err
}

const getStep = `-- name: GetStep :one
SELECT instance_id, position, approver, approvers, fallback, decided_by, decision, reason, decided_at FROM approval.instance_steps WHERE instance_id = $1 AND position = $2
`

type GetStepParams struct {
	InstanceID int64
	Position   int32
}

func (q *Queries) GetStep(ctx context.Context, arg GetStepParams) (ApprovalInstanceStep, error) {
	row := q.db.QueryRow(ctx, getStep, arg.InstanceID, arg.Position)
	var i ApprovalInstanceStep
	err := row.Scan(
		&i.InstanceID,
		&i.Position,
		&i.Approver,
		&i.Approvers,
		&i.Fallback,
		&i.DecidedBy,
		&i.Decision,
		&i.Reason,
		&i.DecidedAt,
	)
	return i, err
}

const inbox = `-- name: Inbox :many
SELECT i.id, i.doc_type, i.doc_id, i.current_step, i.submitted_at, u.name AS submitted_by_name, d.number, d.date
FROM approval.instances i
JOIN approval.instance_steps s ON s.instance_id = i.id AND s.position = i.current_step
JOIN record.documents d ON d.id = i.doc_id
JOIN iam.users u ON u.id = i.submitted_by
WHERE i.status = 'open' AND s.decision IS NULL AND s.approvers @> ARRAY[$1::bigint]
ORDER BY i.submitted_at, i.id
`

type InboxRow struct {
	ID              int64
	DocType         string
	DocID           int64
	CurrentStep     int32
	SubmittedAt     pgtype.Timestamptz
	SubmittedByName string
	Number          string
	Date            pgtype.Date
}

// Open instances waiting for @actor at their current step.
func (q *Queries) Inbox(ctx context.Context, actor int64) ([]InboxRow, error) {
	rows, err := q.db.Query(ctx, inbox, actor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InboxRow
	for rows.Next() {
		var i InboxRow
		if err := rows.Scan(
			&i.ID,
			&i.DocType,
			&i.DocID,
			&i.CurrentStep,
			&i.SubmittedAt,
			&i.SubmittedByName,
			&i.Number,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertInstance = `-- name: InsertInstance :one
INSERT INTO approval.instances (doc_type, doc_id, version, submitted_by, status, current_step, max_levels, fallback_product, fallback_role)
VALUES ($1, $2, $3, $4, 'open', 1, $5, $6, $7) RETURNING id
`

type InsertInstanceParams struct {
	DocType         string
	DocID           int64
	Version         int32
	SubmittedBy     int64
	MaxLevels       int32
	FallbackProduct string
	FallbackRole    string
}

func (q *Queries) InsertInstance(ctx context.Context, arg InsertInstanceParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertInstance,
		arg.DocType,
		arg.DocID,
		arg.Version,
		arg.SubmittedBy,
		arg.MaxLevels,
		arg.FallbackProduct,
		arg.FallbackRole,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertStep = `-- name: InsertStep :exec
INSERT INTO approval.instance_steps (instance_id, position, approver) VALUES ($1, $2, $3)
`

type InsertStepParams struct {
	InstanceID int64
	Position   int32
	Approver   []byte
}

func (q *Queries) InsertStep(ctx context.Context, arg InsertStepParams) error {
	_, err := q.db.Exec(ctx, insertStep, arg.InstanceID, arg.Position, arg.Approver)
	return err
}

const latestInstance = `-- name: LatestInstance :one
SELECT i.id, i.doc_type, i.doc_id, i.version, i.submitted_by, i.submitted_at, i.status, i.current_step, i.max_levels, i.fallback_product, i.fallback_role, u.name AS submitted_by_name FROM approval.instances i JOIN iam.users u ON u.id = i.submitted_by
WHERE i.doc_type = $1 AND i.doc_id = $2 ORDER BY i.id DESC LIMIT 1
`

type LatestInstanceParams struct {
	DocType string
	DocID   int64
}

type LatestInstanceRow struct {
	ID              int64
	DocType         string
	DocID           int64
	Version         int32
	SubmittedBy     int64
	SubmittedAt     pgtype.Timestamptz
	Status          string
	CurrentStep     int32
	MaxLevels       int32
	FallbackProduct string
	FallbackRole    string
	SubmittedByName string
}

func (q *Queries) LatestInstance(ctx context.Context, arg LatestInstanceParams) (LatestInstanceRow, error) {
	row := q.db.QueryRow(ctx, latestInstance, arg.DocType, arg.DocID)
	var i LatestInstanceRow
	err := row.Scan(
		&i.ID,
		&i.DocType,
		&i.DocID,
		&i.Version,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.Status,
		&i.CurrentStep,
		&i.MaxLevels,
		&i.FallbackProduct,
		&i.FallbackRole,
		&i.SubmittedByName,
	)
	return i, err
}

const listRules = `-- name: ListRules :many
SELECT doc_type, steps, max_levels, fallback_product, fallback_role FROM approval.rules ORDER BY doc_type
`

func (q *Queries) ListRules(ctx context.Context) ([]ApprovalRule, error) {
	rows, err := q.db.Query(ctx, listRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApprovalRule
	for rows.Next() {
		var i ApprovalRule
		if err := rows.Scan(
			&i.DocType,
			&i.Steps,
			&i.MaxLevels,
			&i.FallbackProduct,
			&i.FallbackRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, login, name FROM iam.users ORDER BY lower(login)
`

type ListUsersRow struct {
	ID    int64
	Login string
	Name  string
}

// Who a rule may name as approver.
func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.ID, &i.Login, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInstance = `-- name: LockInstance :one
SELECT id, doc_type, doc_id, version, submitted_by, submitted_at, status, current_step, max_levels, fallback_product, fallback_role FROM approval.instances WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockInstance(ctx context.Context, id int64) (ApprovalInstance, error) {
	row := q.db.QueryRow(ctx, lockInstance, id)
	var i ApprovalInstance
	err := row.Scan(
		&i.ID,
		&i.DocType,
		&i.DocID,
		&i.Version,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.Status,
		&i.CurrentStep,
		&i.MaxLevels,
		&i.FallbackProduct,
		&i.FallbackRole,
	)
	return i, err
}

const saveRule = `-- name: SaveRule :exec
INSERT INTO approval.rules (doc_type, steps, max_levels, fallback_product, fallback_role) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (doc_type) DO UPDATE SET steps = $2, max_levels = $3, fallback_product = $4, fallback_role = $5
`

type SaveRuleParams struct {
	DocType         string
	Steps           []byte
	MaxLevels       int32
	FallbackProduct string
	FallbackRole    string
}

func (q *Queries) SaveRule(ctx context.Context, arg SaveRuleParams) error {
	_, err := q.db.Exec(ctx, saveRule,
		arg.DocType,
		arg.Steps,
		arg.MaxLevels,
		arg.FallbackProduct,
		arg.FallbackRole,
	)
	return err
}

const setCurrentStep = `-- name: SetCurrentStep :exec
UPDATE approval.instances SET current_step = $2 WHERE id = $1
`

type SetCurrentStepParams struct {
	ID          int64
	CurrentStep int32
}

func (q *Queries) SetCurrentStep(ctx context.Context, arg SetCurrentStepParams) error {
	_, err := q.db.Exec(ctx, setCurrentStep, arg.ID, arg.CurrentStep)
	return err
}

const startStep = `-- name: StartStep :exec
UPDATE approval.instance_steps SET approvers = $1, fallback = $2 WHERE instance_id = $3 AND position = $4
`

type StartStepParams struct {
	Approvers  []int64
	Fallback   bool
	InstanceID int64
	Position   int32
}

func (q *Queries) StartStep(ctx context.Context, arg StartStepParams) error {
	_, err := q.db.Exec(ctx, startStep,
		arg.Approvers,
		arg.Fallback,
		arg.InstanceID,
		arg.Position,
	)
	return err
}

const stepCount = `-- name: StepCount :one
SELECT count(*) FROM approval.instance_steps WHERE instance_id = $1
`

func (q *Queries) StepCount(ctx context.Context, instanceID int64) (int64, error) {
	row := q.db.QueryRow(ctx, stepCount, instanceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const steps = `-- name: Steps :many
SELECT s.position, s.approvers, s.fallback, s.decision, s.reason, s.decided_at, d.name AS decided_by_name,
       (SELECT coalesce(array_agg(a.name ORDER BY a.name), '{}')::text[] FROM iam.users a WHERE a.id = ANY(s.approvers)) AS approver_names
FROM approval.instance_steps s LEFT JOIN iam.users d ON d.id = s.decided_by
WHERE s.instance_id = $1 ORDER BY s.position
`

type StepsRow struct {
	Position      int32
	Approvers     []int64
	Fallback      bool
	Decision      pgtype.Text
	Reason        pgtype.Text
	DecidedAt     pgtype.Timestamptz
	DecidedByName pgtype.Text
	ApproverNames []string
}

func (q *Queries) Steps(ctx context.Context, instanceID int64) ([]StepsRow, error) {
	rows, err := q.db.Query(ctx, steps, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StepsRow
	for rows.Next() {
		var i StepsRow
		if err := rows.Scan(
			&i.Position,
			&i.Approvers,
			&i.Fallback,
			&i.Decision,
			&i.Reason,
			&i.DecidedAt,
			&i.DecidedByName,
			&i.ApproverNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const within = `-- name: Within :one
WITH RECURSIVE up AS (
    SELECT o.id, o.parent_id FROM iam.org_units o WHERE o.id = $2
    UNION
    SELECT o.id, o.parent_id FROM iam.org_units o JOIN up ON o.id = up.parent_id
)
SELECT EXISTS (SELECT 1 FROM up WHERE up.id = $1::bigint)
`

type WithinParams struct {
	Ancestor int64
	Unit     int64
}

// Whether @unit is @ancestor or below it.
func (q *Queries) Within(ctx context.Context, arg WithinParams) (bool, error) {
	row := q.db.QueryRow(ctx, within, arg.Ancestor, arg.Unit)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
