// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IamOrgUnit struct {
	ID        int64
	ParentID  pgtype.Int8
	Kind      string
	Name      string
	TaxCode   pgtype.Text
	LegalName pgtype.Text
	Address   pgtype.Text
}
