// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpTenantAuthz = `-- name: BumpTenantAuthz :exec
UPDATE iam.authz SET version = version + 1
`

func (q *Queries) BumpTenantAuthz(ctx context.Context) error {
	_, err := q.db.Exec(ctx, bumpTenantAuthz)
	return err
}

const bumpUserAuthz = `-- name: BumpUserAuthz :exec
UPDATE iam.users SET authz_version = authz_version + 1 WHERE id = $1
`

func (q *Queries) BumpUserAuthz(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, bumpUserAuthz, id)
	return err
}

const createOrgUnit = `-- name: CreateOrgUnit :one
INSERT INTO iam.org_units (parent_id, kind, name, tax_code, legal_name, address)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id
`

type CreateOrgUnitParams struct {
	ParentID  pgtype.Int8
	Kind      string
	Name      string
	TaxCode   pgtype.Text
	LegalName pgtype.Text
	Address   pgtype.Text
}

func (q *Queries) CreateOrgUnit(ctx context.Context, arg CreateOrgUnitParams) (int64, error) {
	row := q.db.QueryRow(ctx, createOrgUnit,
		arg.ParentID,
		arg.Kind,
		arg.Name,
		arg.TaxCode,
		arg.LegalName,
		arg.Address,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO iam.sessions (token_hash, user_id, expires_at) VALUES ($1, $2, now() + interval '14 days')
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    int64
}

// Fixed lifetime from login; activity does not extend it.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO iam.users (login, name, password_hash) VALUES ($1, $2, $3) RETURNING id
`

type CreateUserParams struct {
	Login        string
	Name         string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Login, arg.Name, arg.PasswordHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM iam.sessions WHERE user_id = $1 AND expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :one
DELETE FROM iam.sessions WHERE token_hash = $1 RETURNING user_id
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) (int64, error) {
	row := q.db.QueryRow(ctx, deleteSession, tokenHash)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getOrgUnit = `-- name: GetOrgUnit :one
SELECT id, parent_id, kind, name, tax_code, legal_name, address FROM iam.org_units WHERE id = $1
`

func (q *Queries) GetOrgUnit(ctx context.Context, id int64) (IamOrgUnit, error) {
	row := q.db.QueryRow(ctx, getOrgUnit, id)
	var i IamOrgUnit
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.TaxCode,
		&i.LegalName,
		&i.Address,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT s.user_id, u.authz_version, (SELECT version FROM iam.authz) AS tenant_version
FROM iam.sessions s JOIN iam.users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now()
`

type GetSessionRow struct {
	UserID        int64
	AuthzVersion  int64
	TenantVersion int64
}

func (q *Queries) GetSession(ctx context.Context, tokenHash []byte) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, tokenHash)
	var i GetSessionRow
	err := row.Scan(&i.UserID, &i.AuthzVersion, &i.TenantVersion)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT u.id, u.login, u.name, u.email, u.locale, u.authz_version, (SELECT version FROM iam.authz) AS tenant_version
FROM iam.users u WHERE u.id = $1
`

type GetUserRow struct {
	ID            int64
	Login         string
	Name          string
	Email         pgtype.Text
	Locale        pgtype.Text
	AuthzVersion  int64
	TenantVersion int64
}

func (q *Queries) GetUser(ctx context.Context, id int64) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Name,
		&i.Email,
		&i.Locale,
		&i.AuthzVersion,
		&i.TenantVersion,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, password_hash FROM iam.users WHERE lower(login) = lower($1)
`

type GetUserByLoginRow struct {
	ID           int64
	PasswordHash string
}

func (q *Queries) GetUserByLogin(ctx context.Context, lower string) (GetUserByLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, lower)
	var i GetUserByLoginRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}

const grantRole = `-- name: GrantRole :one
INSERT INTO iam.user_roles (user_id, product, role, org_unit_id) VALUES ($1, $2, $3, $4) RETURNING id
`

type GrantRoleParams struct {
	UserID    int64
	Product   string
	Role      string
	OrgUnitID pgtype.Int8
}

func (q *Queries) GrantRole(ctx context.Context, arg GrantRoleParams) (int64, error) {
	row := q.db.QueryRow(ctx, grantRole,
		arg.UserID,
		arg.Product,
		arg.Role,
		arg.OrgUnitID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const legalEntityOf = `-- name: LegalEntityOf :one
WITH RECURSIVE up AS (
    SELECT o.id, o.parent_id, o.kind, 0 AS depth FROM iam.org_units o WHERE o.id = $1
    UNION ALL
    SELECT u.id, u.parent_id, u.kind, up.depth + 1 FROM iam.org_units u JOIN up ON u.id = up.parent_id
    WHERE up.kind <> 'company'
)
SELECT up.id FROM up WHERE up.kind = 'company' ORDER BY up.depth LIMIT 1
`

// The nearest company at or above the unit.
func (q *Queries) LegalEntityOf(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, legalEntityOf, id)
	err := row.Scan(&id)
	return id, err
}

const listOrgUnits = `-- name: ListOrgUnits :many
SELECT id, parent_id, kind, name, tax_code, legal_name, address FROM iam.org_units ORDER BY name, id
`

func (q *Queries) ListOrgUnits(ctx context.Context) ([]IamOrgUnit, error) {
	rows, err := q.db.Query(ctx, listOrgUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IamOrgUnit
	for rows.Next() {
		var i IamOrgUnit
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Kind,
			&i.Name,
			&i.TaxCode,
			&i.LegalName,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, login, name, email FROM iam.users ORDER BY lower(login)
`

type ListUsersRow struct {
	ID    int64
	Login string
	Name  string
	Email pgtype.Text
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Login,
			&i.Name,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrgUnits = `-- name: LockOrgUnits :exec
LOCK TABLE iam.org_units IN SHARE ROW EXCLUSIVE MODE
`

// Serialises tree writes so concurrent moves cannot build a cycle.
func (q *Queries) LockOrgUnits(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockOrgUnits)
	return err
}

const orgTreeViolations = `-- name: OrgTreeViolations :one
WITH RECURSIVE walk AS (
    SELECT id, CASE WHEN kind = 'company' THEN id END AS company, kind NOT IN ('company', 'group') AS bad
    FROM iam.org_units WHERE parent_id IS NULL
    UNION ALL
    SELECT u.id, CASE WHEN u.kind = 'company' THEN u.id ELSE w.company END,
           CASE WHEN u.kind IN ('company', 'group') THEN w.company IS NOT NULL ELSE w.company IS NULL END
    FROM iam.org_units u JOIN walk w ON u.parent_id = w.id
)
SELECT ((SELECT count(*) FROM iam.org_units) - (SELECT count(*) FROM walk))::bigint AS unreachable,
       (SELECT count(*) FROM walk WHERE bad) AS misplaced
`

type OrgTreeViolationsRow struct {
	Unreachable int64
	Misplaced   int64
}

// Walks down from the roots carrying the nearest company. Nodes not reached sit on a cycle.
func (q *Queries) OrgTreeViolations(ctx context.Context) (OrgTreeViolationsRow, error) {
	row := q.db.QueryRow(ctx, orgTreeViolations)
	var i OrgTreeViolationsRow
	err := row.Scan(&i.Unreachable, &i.Misplaced)
	return i, err
}

const revokeRole = `-- name: RevokeRole :one
DELETE FROM iam.user_roles WHERE id = $1 AND user_id = $2 RETURNING product, role, org_unit_id
`

type RevokeRoleParams struct {
	ID     int64
	UserID int64
}

type RevokeRoleRow struct {
	Product   string
	Role      string
	OrgUnitID pgtype.Int8
}

func (q *Queries) RevokeRole(ctx context.Context, arg RevokeRoleParams) (RevokeRoleRow, error) {
	row := q.db.QueryRow(ctx, revokeRole, arg.ID, arg.UserID)
	var i RevokeRoleRow
	err := row.Scan(&i.Product, &i.Role, &i.OrgUnitID)
	return i, err
}

const setLocale = `-- name: SetLocale :exec
UPDATE iam.users SET locale = $2 WHERE id = $1
`

type SetLocaleParams struct {
	ID     int64
	Locale pgtype.Text
}

func (q *Queries) SetLocale(ctx context.Context, arg SetLocaleParams) error {
	_, err := q.db.Exec(ctx, setLocale, arg.ID, arg.Locale)
	return err
}

const setUserEmail = `-- name: SetUserEmail :execrows
UPDATE iam.users SET email = $2 WHERE id = $1
`

type SetUserEmailParams struct {
	ID    int64
	Email pgtype.Text
}

func (q *Queries) SetUserEmail(ctx context.Context, arg SetUserEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserEmail, arg.ID, arg.Email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const shareOrgUnits = `-- name: ShareOrgUnits :exec
LOCK TABLE iam.org_units IN SHARE MODE
`

// Holds tree writes off, not other readers of the tree.
func (q *Queries) ShareOrgUnits(ctx context.Context) error {
	_, err := q.db.Exec(ctx, shareOrgUnits)
	return err
}

const subtrees = `-- name: Subtrees :many
WITH RECURSIVE t AS (
    SELECT id FROM iam.org_units WHERE id = ANY($1::bigint[])
    UNION
    SELECT u.id FROM iam.org_units u JOIN t ON u.parent_id = t.id
)
SELECT id FROM t ORDER BY id
`

func (q *Queries) Subtrees(ctx context.Context, roots []int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, subtrees, roots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrgUnit = `-- name: UpdateOrgUnit :execrows
UPDATE iam.org_units SET parent_id = $2, kind = $3, name = $4, tax_code = $5, legal_name = $6, address = $7
WHERE id = $1
`

type UpdateOrgUnitParams struct {
	ID        int64
	ParentID  pgtype.Int8
	Kind      string
	Name      string
	TaxCode   pgtype.Text
	LegalName pgtype.Text
	Address   pgtype.Text
}

func (q *Queries) UpdateOrgUnit(ctx context.Context, arg UpdateOrgUnitParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrgUnit,
		arg.ID,
		arg.ParentID,
		arg.Kind,
		arg.Name,
		arg.TaxCode,
		arg.LegalName,
		arg.Address,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const userRoles = `-- name: UserRoles :many
SELECT r.id, r.product, r.role, r.org_unit_id, u.name AS org_unit_name
FROM iam.user_roles r LEFT JOIN iam.org_units u ON u.id = r.org_unit_id
WHERE r.user_id = $1 ORDER BY r.product, r.role, u.name NULLS FIRST
`

type UserRolesRow struct {
	ID          int64
	Product     string
	Role        string
	OrgUnitID   pgtype.Int8
	OrgUnitName pgtype.Text
}

func (q *Queries) UserRoles(ctx context.Context, userID int64) ([]UserRolesRow, error) {
	rows, err := q.db.Query(ctx, userRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserRolesRow
	for rows.Next() {
		var i UserRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Product,
			&i.Role,
			&i.OrgUnitID,
			&i.OrgUnitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usersWithRole = `-- name: UsersWithRole :many
WITH RECURSIVE up AS (
    SELECT o.id, o.parent_id FROM iam.org_units o WHERE o.id = $3
    UNION
    SELECT u.id, u.parent_id FROM iam.org_units u JOIN up ON u.id = up.parent_id
)
SELECT DISTINCT r.user_id FROM iam.user_roles r
WHERE r.product = $1 AND r.role = $2 AND (r.org_unit_id IS NULL OR r.org_unit_id IN (SELECT up.id FROM up))
ORDER BY r.user_id
`

type UsersWithRoleParams struct {
	Product string
	Role    string
	Unit    int64
}

// Users holding the role tenant-wide or at the unit or one of its ancestors.
func (q *Queries) UsersWithRole(ctx context.Context, arg UsersWithRoleParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, usersWithRole, arg.Product, arg.Role, arg.Unit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
