// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

type SalesItem struct {
	ID      int64
	Code    string
	Name    string
	Unit    string
	Price   int64
	VatRate string
	Active  bool
}
