// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const anyCatalog = `-- name: AnyCatalog :one
SELECT (EXISTS (SELECT 1 FROM sales.customers) OR EXISTS (SELECT 1 FROM sales.items))::bool AS any
`

// Items count as Sales data too, though they are no record type.
func (q *Queries) AnyCatalog(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, anyCatalog)
	var any bool
	err := row.Scan(&any)
	return any, err
}

const copyCustomer = `-- name: CopyCustomer :one
UPDATE sales.headers h
SET customer_code = c.code, customer_name = c.name, customer_tax_code = c.tax_code, customer_address = c.address,
    customer_phone = c.phone, customer_email = c.email, contact_name = c.contact_name
FROM sales.customers c
WHERE h.id = $1 AND c.id = h.customer_id
RETURNING c.active
`

// Takes the customer's details as they are now onto a document being sent; returns whether
// the customer is active.
func (q *Queries) CopyCustomer(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, copyCustomer, id)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO sales.customers (code, name, tax_code, address, phone, email, contact_name, payment_terms, org_unit_id, active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id
`

type CreateCustomerParams struct {
	Code         string
	Name         string
	TaxCode      pgtype.Text
	Address      pgtype.Text
	Phone        pgtype.Text
	Email        pgtype.Text
	ContactName  pgtype.Text
	PaymentTerms pgtype.Text
	OrgUnitID    int64
	Active       bool
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (int64, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.Code,
		arg.Name,
		arg.TaxCode,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.ContactName,
		arg.PaymentTerms,
		arg.OrgUnitID,
		arg.Active,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO sales.items (code, name, unit, price, vat_rate, active) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id
`

type CreateItemParams struct {
	Code    string
	Name    string
	Unit    string
	Price   int64
	VatRate string
	Active  bool
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (int64, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.Code,
		arg.Name,
		arg.Unit,
		arg.Price,
		arg.VatRate,
		arg.Active,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const customerActive = `-- name: CustomerActive :one
SELECT active FROM sales.customers WHERE id = $1 FOR SHARE
`

// Read under a share lock, so the customer cannot be deactivated while a document posts.
func (q *Queries) CustomerActive(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, customerActive, id)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const deleteHeader = `-- name: DeleteHeader :exec
DELETE FROM sales.headers WHERE id = $1
`

func (q *Queries) DeleteHeader(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteHeader, id)
	return err
}

const deleteLines = `-- name: DeleteLines :exec
DELETE FROM sales.lines WHERE doc_id = $1
`

func (q *Queries) DeleteLines(ctx context.Context, docID int64) error {
	_, err := q.db.Exec(ctx, deleteLines, docID)
	return err
}

const getCustomer = `-- name: GetCustomer :one
SELECT c.id, c.code, c.name, c.tax_code, c.address, c.phone, c.email, c.contact_name, c.payment_terms, c.org_unit_id, c.active, u.name AS org_unit_name
FROM sales.customers c JOIN iam.org_units u ON u.id = c.org_unit_id
WHERE c.id = $1
`

type GetCustomerRow struct {
	ID           int64
	Code         string
	Name         string
	TaxCode      pgtype.Text
	Address      pgtype.Text
	Phone        pgtype.Text
	Email        pgtype.Text
	ContactName  pgtype.Text
	PaymentTerms pgtype.Text
	OrgUnitID    int64
	Active       bool
	OrgUnitName  string
}

func (q *Queries) GetCustomer(ctx context.Context, id int64) (GetCustomerRow, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i GetCustomerRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.TaxCode,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.ContactName,
		&i.PaymentTerms,
		&i.OrgUnitID,
		&i.Active,
		&i.OrgUnitName,
	)
	return i, err
}

const getHeader = `-- name: GetHeader :one
SELECT h.id, h.kind, h.request_id, h.customer_id, h.customer_code, h.customer_name, h.customer_tax_code, h.customer_address, h.customer_phone, h.customer_email, h.contact_name, h.valid_until, h.delivery_date, h.quote_id, h.payment_terms, h.delivery_terms, h.note, h.subtotal, h.discount_total, h.vat_total, h.total, d.number, d.status, d.version, d.date, d.org_unit_id, d.legal_entity_id, u.name AS org_unit_name,
       q.number AS quote_number
FROM sales.headers h
JOIN record.documents d ON d.id = h.id
JOIN iam.org_units u ON u.id = d.org_unit_id
LEFT JOIN record.documents q ON q.id = h.quote_id
WHERE h.id = $1
`

type GetHeaderRow struct {
	ID              int64
	Kind            string
	RequestID       pgtype.UUID
	CustomerID      int64
	CustomerCode    string
	CustomerName    string
	CustomerTaxCode pgtype.Text
	CustomerAddress pgtype.Text
	CustomerPhone   pgtype.Text
	CustomerEmail   pgtype.Text
	ContactName     pgtype.Text
	ValidUntil      pgtype.Date
	DeliveryDate    pgtype.Date
	QuoteID         pgtype.Int8
	PaymentTerms    pgtype.Text
	DeliveryTerms   pgtype.Text
	Note            pgtype.Text
	Subtotal        int64
	DiscountTotal   int64
	VatTotal        int64
	Total           int64
	Number          string
	Status          string
	Version         int32
	Date            pgtype.Date
	OrgUnitID       int64
	LegalEntityID   int64
	OrgUnitName     string
	QuoteNumber     pgtype.Text
}

func (q *Queries) GetHeader(ctx context.Context, id int64) (GetHeaderRow, error) {
	row := q.db.QueryRow(ctx, getHeader, id)
	var i GetHeaderRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.RequestID,
		&i.CustomerID,
		&i.CustomerCode,
		&i.CustomerName,
		&i.CustomerTaxCode,
		&i.CustomerAddress,
		&i.CustomerPhone,
		&i.CustomerEmail,
		&i.ContactName,
		&i.ValidUntil,
		&i.DeliveryDate,
		&i.QuoteID,
		&i.PaymentTerms,
		&i.DeliveryTerms,
		&i.Note,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.VatTotal,
		&i.Total,
		&i.Number,
		&i.Status,
		&i.Version,
		&i.Date,
		&i.OrgUnitID,
		&i.LegalEntityID,
		&i.OrgUnitName,
		&i.QuoteNumber,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id, code, name, unit, price, vat_rate, active FROM sales.items WHERE id = $1
`

func (q *Queries) GetItem(ctx context.Context, id int64) (SalesItem, error) {
	row := q.db.QueryRow(ctx, getItem, id)
	var i SalesItem
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Unit,
		&i.Price,
		&i.VatRate,
		&i.Active,
	)
	return i, err
}

const getLines = `-- name: GetLines :many
SELECT item_id, item_code, description, unit, quantity::text AS quantity, unit_price,
       discount_percent::text AS discount_percent, vat_rate, amount, discount, vat
FROM sales.lines WHERE doc_id = $1 ORDER BY position
`

type GetLinesRow struct {
	ItemID          int64
	ItemCode        string
	Description     string
	Unit            string
	Quantity        string
	UnitPrice       int64
	DiscountPercent string
	VatRate         string
	Amount          int64
	Discount        int64
	Vat             int64
}

func (q *Queries) GetLines(ctx context.Context, docID int64) ([]GetLinesRow, error) {
	rows, err := q.db.Query(ctx, getLines, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLinesRow
	for rows.Next() {
		var i GetLinesRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemCode,
			&i.Description,
			&i.Unit,
			&i.Quantity,
			&i.UnitPrice,
			&i.DiscountPercent,
			&i.VatRate,
			&i.Amount,
			&i.Discount,
			&i.Vat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const headerByRequest = `-- name: HeaderByRequest :one
SELECT id, kind FROM sales.headers WHERE request_id = CAST($1::text AS uuid)
`

type HeaderByRequestRow struct {
	ID   int64
	Kind string
}

func (q *Queries) HeaderByRequest(ctx context.Context, requestID string) (HeaderByRequestRow, error) {
	row := q.db.QueryRow(ctx, headerByRequest, requestID)
	var i HeaderByRequestRow
	err := row.Scan(&i.ID, &i.Kind)
	return i, err
}

const insertHeader = `-- name: InsertHeader :exec
INSERT INTO sales.headers (id, kind, request_id, customer_id, customer_code, customer_name, customer_tax_code,
    customer_address, customer_phone, customer_email, contact_name, valid_until, delivery_date, quote_id,
    payment_terms, delivery_terms, note, subtotal, discount_total, vat_total, total)
VALUES ($1, $2, CAST($3::text AS uuid), $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19, $20, $21)
`

type InsertHeaderParams struct {
	ID              int64
	Kind            string
	RequestID       string
	CustomerID      int64
	CustomerCode    string
	CustomerName    string
	CustomerTaxCode pgtype.Text
	CustomerAddress pgtype.Text
	CustomerPhone   pgtype.Text
	CustomerEmail   pgtype.Text
	ContactName     pgtype.Text
	ValidUntil      pgtype.Date
	DeliveryDate    pgtype.Date
	QuoteID         pgtype.Int8
	PaymentTerms    pgtype.Text
	DeliveryTerms   pgtype.Text
	Note            pgtype.Text
	Subtotal        int64
	DiscountTotal   int64
	VatTotal        int64
	Total           int64
}

func (q *Queries) InsertHeader(ctx context.Context, arg InsertHeaderParams) error {
	_, err := q.db.Exec(ctx, insertHeader,
		arg.ID,
		arg.Kind,
		arg.RequestID,
		arg.CustomerID,
		arg.CustomerCode,
		arg.CustomerName,
		arg.CustomerTaxCode,
		arg.CustomerAddress,
		arg.CustomerPhone,
		arg.CustomerEmail,
		arg.ContactName,
		arg.ValidUntil,
		arg.DeliveryDate,
		arg.QuoteID,
		arg.PaymentTerms,
		arg.DeliveryTerms,
		arg.Note,
		arg.Subtotal,
		arg.DiscountTotal,
		arg.VatTotal,
		arg.Total,
	)
	return err
}

const insertLine = `-- name: InsertLine :exec
INSERT INTO sales.lines (doc_id, position, item_id, item_code, description, unit, quantity, unit_price,
    discount_percent, vat_rate, amount, discount, vat)
VALUES ($1, $2, $3, $4, $5, $6, CAST($7::text AS numeric), $8,
    CAST($9::text AS numeric), $10, $11, $12, $13)
`

type InsertLineParams struct {
	DocID           int64
	Position        int32
	ItemID          int64
	ItemCode        string
	Description     string
	Unit            string
	Quantity        string
	UnitPrice       int64
	DiscountPercent string
	VatRate         string
	Amount          int64
	Discount        int64
	Vat             int64
}

func (q *Queries) InsertLine(ctx context.Context, arg InsertLineParams) error {
	_, err := q.db.Exec(ctx, insertLine,
		arg.DocID,
		arg.Position,
		arg.ItemID,
		arg.ItemCode,
		arg.Description,
		arg.Unit,
		arg.Quantity,
		arg.UnitPrice,
		arg.DiscountPercent,
		arg.VatRate,
		arg.Amount,
		arg.Discount,
		arg.Vat,
	)
	return err
}

const itemsByID = `-- name: ItemsByID :many
SELECT id, code, name, unit, price, vat_rate, active FROM sales.items WHERE id = ANY($1::bigint[])
`

func (q *Queries) ItemsByID(ctx context.Context, ids []int64) ([]SalesItem, error) {
	rows, err := q.db.Query(ctx, itemsByID, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesItem
	for rows.Next() {
		var i SalesItem
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Unit,
			&i.Price,
			&i.VatRate,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomers = `-- name: ListCustomers :many
SELECT c.id, c.code, c.name, c.tax_code, c.phone, c.payment_terms, c.org_unit_id, u.name AS org_unit_name, c.active, count(*) OVER () AS total
FROM sales.customers c JOIN iam.org_units u ON u.id = c.org_unit_id
WHERE ($1::bool OR c.org_unit_id = ANY($2::bigint[]))
  AND ($3::text = '' OR c.code ILIKE '%' || $3 || '%' OR c.name ILIKE '%' || $3 || '%' OR c.tax_code ILIKE '%' || $3 || '%')
  AND ($4::bool IS NULL OR c.active = $4)
ORDER BY
    CASE WHEN $5::text = 'code' THEN lower(c.code) END,
    CASE WHEN $5 = '-code' THEN lower(c.code) END DESC,
    CASE WHEN $5 = 'name' THEN c.name END,
    CASE WHEN $5 = '-name' THEN c.name END DESC,
    c.id
LIMIT $7 OFFSET $6
`

type ListCustomersParams struct {
	AllUnits bool
	Units    []int64
	Q        string
	Active   pgtype.Bool
	Sort     string
	Off      int32
	Lim      int32
}

type ListCustomersRow struct {
	ID           int64
	Code         string
	Name         string
	TaxCode      pgtype.Text
	Phone        pgtype.Text
	PaymentTerms pgtype.Text
	OrgUnitID    int64
	OrgUnitName  string
	Active       bool
	Total        int64
}

// Scope filter: @all_units or org_unit_id in @units.
func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]ListCustomersRow, error) {
	rows, err := q.db.Query(ctx, listCustomers,
		arg.AllUnits,
		arg.Units,
		arg.Q,
		arg.Active,
		arg.Sort,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomersRow
	for rows.Next() {
		var i ListCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.TaxCode,
			&i.Phone,
			&i.PaymentTerms,
			&i.OrgUnitID,
			&i.OrgUnitName,
			&i.Active,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeaders = `-- name: ListHeaders :many
SELECT h.id, d.number, d.status, d.date, h.customer_id, h.customer_code, h.customer_name, h.valid_until, h.total,
       u.name AS org_unit_name, (h.quote_id IS NOT NULL)::bool AS from_quote,
       EXISTS (
           SELECT 1 FROM sales.headers oh JOIN record.documents od ON od.id = oh.id
           WHERE oh.quote_id = h.id AND od.status <> 'cancelled'
       ) AS ordered,
       count(*) OVER () AS total_rows
FROM sales.headers h
JOIN record.documents d ON d.id = h.id
JOIN iam.org_units u ON u.id = d.org_unit_id
WHERE h.kind = $1::text
  AND ($2::bool OR d.org_unit_id = ANY($3::bigint[]))
  AND ($4::text = '' OR d.status = $4)
  AND ($5::bigint IS NULL OR h.customer_id = $5)
  AND ($6::text = '' OR d.number ILIKE '%' || $6 || '%' OR h.customer_name ILIKE '%' || $6 || '%' OR h.customer_code ILIKE '%' || $6 || '%')
ORDER BY
    CASE WHEN $7::text = 'date' THEN d.date END,
    CASE WHEN $7 = '-date' THEN d.date END DESC,
    CASE WHEN $7 = 'number' THEN d.number END,
    CASE WHEN $7 = '-number' THEN d.number END DESC,
    CASE WHEN $7 = 'total' THEN h.total END,
    CASE WHEN $7 = '-total' THEN h.total END DESC,
    h.id DESC
LIMIT $9 OFFSET $8
`

type ListHeadersParams struct {
	Kind       string
	AllUnits   bool
	Units      []int64
	Status     string
	CustomerID pgtype.Int8
	Q          string
	Sort       string
	Off        int32
	Lim        int32
}

type ListHeadersRow struct {
	ID           int64
	Number       string
	Status       string
	Date         pgtype.Date
	CustomerID   int64
	CustomerCode string
	CustomerName string
	ValidUntil   pgtype.Date
	Total        int64
	OrgUnitName  string
	FromQuote    bool
	Ordered      bool
	TotalRows    int64
}

// Scope filter: @all_units or the document's org unit in @units.
func (q *Queries) ListHeaders(ctx context.Context, arg ListHeadersParams) ([]ListHeadersRow, error) {
	rows, err := q.db.Query(ctx, listHeaders,
		arg.Kind,
		arg.AllUnits,
		arg.Units,
		arg.Status,
		arg.CustomerID,
		arg.Q,
		arg.Sort,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHeadersRow
	for rows.Next() {
		var i ListHeadersRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Status,
			&i.Date,
			&i.CustomerID,
			&i.CustomerCode,
			&i.CustomerName,
			&i.ValidUntil,
			&i.Total,
			&i.OrgUnitName,
			&i.FromQuote,
			&i.Ordered,
			&i.TotalRows,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT id, code, name, unit, price, vat_rate, active, count(*) OVER () AS total
FROM sales.items
WHERE ($1::text = '' OR code ILIKE '%' || $1 || '%' OR name ILIKE '%' || $1 || '%')
  AND ($2::bool IS NULL OR active = $2)
ORDER BY lower(code), id
LIMIT $4 OFFSET $3
`

type ListItemsParams struct {
	Q      string
	Active pgtype.Bool
	Off    int32
	Lim    int32
}

type ListItemsRow struct {
	ID      int64
	Code    string
	Name    string
	Unit    string
	Price   int64
	VatRate string
	Active  bool
	Total   int64
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]ListItemsRow, error) {
	rows, err := q.db.Query(ctx, listItems,
		arg.Q,
		arg.Active,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsRow
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Unit,
			&i.Price,
			&i.VatRate,
			&i.Active,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveOrder = `-- name: LiveOrder :one
SELECT d.id, d.number, d.status
FROM sales.headers h JOIN record.documents d ON d.id = h.id
WHERE h.quote_id = $1 AND d.status <> 'cancelled'
`

type LiveOrderRow struct {
	ID     int64
	Number string
	Status string
}

// The order made from a quotation that is not cancelled; at most one, since making another
// holds the quotation's row lock and finds this one first.
func (q *Queries) LiveOrder(ctx context.Context, quoteID pgtype.Int8) (LiveOrderRow, error) {
	row := q.db.QueryRow(ctx, liveOrder, quoteID)
	var i LiveOrderRow
	err := row.Scan(&i.ID, &i.Number, &i.Status)
	return i, err
}

const lockCustomer = `-- name: LockCustomer :exec
SELECT 1 FROM sales.customers WHERE id = $1 FOR NO KEY UPDATE
`

// NO KEY: documents referencing the customer stay creatable meanwhile.
func (q *Queries) LockCustomer(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, lockCustomer, id)
	return err
}

const printLegalEntity = `-- name: PrintLegalEntity :one
SELECT coalesce(legal_name, name)::text AS name, tax_code, address FROM iam.org_units WHERE id = $1
`

type PrintLegalEntityRow struct {
	Name    string
	TaxCode pgtype.Text
	Address pgtype.Text
}

func (q *Queries) PrintLegalEntity(ctx context.Context, id int64) (PrintLegalEntityRow, error) {
	row := q.db.QueryRow(ctx, printLegalEntity, id)
	var i PrintLegalEntityRow
	err := row.Scan(&i.Name, &i.TaxCode, &i.Address)
	return i, err
}

const updateCustomer = `-- name: UpdateCustomer :exec
UPDATE sales.customers
SET code = $2, name = $3, tax_code = $4, address = $5, phone = $6, email = $7, contact_name = $8,
    payment_terms = $9, org_unit_id = $10, active = $11
WHERE id = $1
`

type UpdateCustomerParams struct {
	ID           int64
	Code         string
	Name         string
	TaxCode      pgtype.Text
	Address      pgtype.Text
	Phone        pgtype.Text
	Email        pgtype.Text
	ContactName  pgtype.Text
	PaymentTerms pgtype.Text
	OrgUnitID    int64
	Active       bool
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) error {
	_, err := q.db.Exec(ctx, updateCustomer,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.TaxCode,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.ContactName,
		arg.PaymentTerms,
		arg.OrgUnitID,
		arg.Active,
	)
	return err
}

const updateHeader = `-- name: UpdateHeader :exec
UPDATE sales.headers
SET customer_id = $2, customer_code = $3, customer_name = $4, customer_tax_code = $5, customer_address = $6,
    customer_phone = $7, customer_email = $8, contact_name = $9, valid_until = $10, delivery_date = $11,
    payment_terms = $12, delivery_terms = $13, note = $14, subtotal = $15, discount_total = $16,
    vat_total = $17, total = $18
WHERE id = $1
`

type UpdateHeaderParams struct {
	ID              int64
	CustomerID      int64
	CustomerCode    string
	CustomerName    string
	CustomerTaxCode pgtype.Text
	CustomerAddress pgtype.Text
	CustomerPhone   pgtype.Text
	CustomerEmail   pgtype.Text
	ContactName     pgtype.Text
	ValidUntil      pgtype.Date
	DeliveryDate    pgtype.Date
	PaymentTerms    pgtype.Text
	DeliveryTerms   pgtype.Text
	Note            pgtype.Text
	Subtotal        int64
	DiscountTotal   int64
	VatTotal        int64
	Total           int64
}

func (q *Queries) UpdateHeader(ctx context.Context, arg UpdateHeaderParams) error {
	_, err := q.db.Exec(ctx, updateHeader,
		arg.ID,
		arg.CustomerID,
		arg.CustomerCode,
		arg.CustomerName,
		arg.CustomerTaxCode,
		arg.CustomerAddress,
		arg.CustomerPhone,
		arg.CustomerEmail,
		arg.ContactName,
		arg.ValidUntil,
		arg.DeliveryDate,
		arg.PaymentTerms,
		arg.DeliveryTerms,
		arg.Note,
		arg.Subtotal,
		arg.DiscountTotal,
		arg.VatTotal,
		arg.Total,
	)
	return err
}

const updateItem = `-- name: UpdateItem :execrows
UPDATE sales.items SET code = $2, name = $3, unit = $4, price = $5, vat_rate = $6, active = $7 WHERE id = $1
`

type UpdateItemParams struct {
	ID      int64
	Code    string
	Name    string
	Unit    string
	Price   int64
	VatRate string
	Active  bool
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateItem,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Unit,
		arg.Price,
		arg.VatRate,
		arg.Active,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
