// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AttachmentFile struct {
	ID          int64
	DocType     string
	DocID       int64
	FileID      string
	Name        string
	Size        int64
	ContentType string
	UploadedBy  int64
	UploadedAt  pgtype.Timestamptz
}
