// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFile = `-- name: CreateFile :one
INSERT INTO attachment.files (doc_type, doc_id, file_id, name, size, content_type, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id
`

type CreateFileParams struct {
	DocType     string
	DocID       int64
	FileID      string
	Name        string
	Size        int64
	ContentType string
	UploadedBy  int64
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (int64, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.DocType,
		arg.DocID,
		arg.FileID,
		arg.Name,
		arg.Size,
		arg.ContentType,
		arg.UploadedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteFile = `-- name: DeleteFile :one
DELETE FROM attachment.files WHERE id = $1 RETURNING id, doc_type, doc_id, file_id, name, size, content_type, uploaded_by, uploaded_at
`

func (q *Queries) DeleteFile(ctx context.Context, id int64) (AttachmentFile, error) {
	row := q.db.QueryRow(ctx, deleteFile, id)
	var i AttachmentFile
	err := row.Scan(
		&i.ID,
		&i.DocType,
		&i.DocID,
		&i.FileID,
		&i.Name,
		&i.Size,
		&i.ContentType,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const deleteRecordFiles = `-- name: DeleteRecordFiles :exec
DELETE FROM attachment.files WHERE doc_type = $1 AND doc_id = $2
`

type DeleteRecordFilesParams struct {
	DocType string
	DocID   int64
}

func (q *Queries) DeleteRecordFiles(ctx context.Context, arg DeleteRecordFilesParams) error {
	_, err := q.db.Exec(ctx, deleteRecordFiles, arg.DocType, arg.DocID)
	return err
}

const getFile = `-- name: GetFile :one
SELECT id, doc_type, doc_id, file_id, name, size, content_type, uploaded_by, uploaded_at FROM attachment.files WHERE id = $1
`

func (q *Queries) GetFile(ctx context.Context, id int64) (AttachmentFile, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i AttachmentFile
	err := row.Scan(
		&i.ID,
		&i.DocType,
		&i.DocID,
		&i.FileID,
		&i.Name,
		&i.Size,
		&i.ContentType,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const knownFiles = `-- name: KnownFiles :many
SELECT file_id FROM attachment.files WHERE file_id = ANY($1::text[])
`

func (q *Queries) KnownFiles(ctx context.Context, ids []string) ([]string, error) {
	rows, err := q.db.Query(ctx, knownFiles, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var file_id string
		if err := rows.Scan(&file_id); err != nil {
			return nil, err
		}
		items = append(items, file_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiles = `-- name: ListFiles :many
SELECT f.id, f.doc_type, f.doc_id, f.file_id, f.name, f.size, f.content_type, f.uploaded_by, f.uploaded_at, u.name AS uploaded_by_name
FROM attachment.files f JOIN iam.users u ON u.id = f.uploaded_by
WHERE f.doc_type = $1 AND f.doc_id = $2
ORDER BY f.id
`

type ListFilesParams struct {
	DocType string
	DocID   int64
}

type ListFilesRow struct {
	ID             int64
	DocType        string
	DocID          int64
	FileID         string
	Name           string
	Size           int64
	ContentType    string
	UploadedBy     int64
	UploadedAt     pgtype.Timestamptz
	UploadedByName string
}

func (q *Queries) ListFiles(ctx context.Context, arg ListFilesParams) ([]ListFilesRow, error) {
	rows, err := q.db.Query(ctx, listFiles, arg.DocType, arg.DocID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilesRow
	for rows.Next() {
		var i ListFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.DocType,
			&i.DocID,
			&i.FileID,
			&i.Name,
			&i.Size,
			&i.ContentType,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.UploadedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
