// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPin = `-- name: CreatePin :exec
INSERT INTO printing.pins (doc_type, doc_id, layout, locale, blocks) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type CreatePinParams struct {
	DocType string
	DocID   int64
	Layout  int32
	Locale  string
	Blocks  []byte
}

func (q *Queries) CreatePin(ctx context.Context, arg CreatePinParams) error {
	_, err := q.db.Exec(ctx, createPin,
		arg.DocType,
		arg.DocID,
		arg.Layout,
		arg.Locale,
		arg.Blocks,
	)
	return err
}

const createSnapshots = `-- name: CreateSnapshots :exec
INSERT INTO printing.snapshots (doc_type, doc_id, part, position, data)
SELECT $1::text, $2::bigint, unnest($3::bigint[]), unnest($4::int[]), unnest($5::bytea[])
`

type CreateSnapshotsParams struct {
	DocType   string
	DocID     int64
	Parts     []int64
	Positions []int32
	Data      [][]byte
}

func (q *Queries) CreateSnapshots(ctx context.Context, arg CreateSnapshotsParams) error {
	_, err := q.db.Exec(ctx, createSnapshots,
		arg.DocType,
		arg.DocID,
		arg.Parts,
		arg.Positions,
		arg.Data,
	)
	return err
}

const getPin = `-- name: GetPin :one
SELECT layout, locale, blocks FROM printing.pins WHERE doc_type = $1 AND doc_id = $2
`

type GetPinParams struct {
	DocType string
	DocID   int64
}

type GetPinRow struct {
	Layout int32
	Locale string
	Blocks []byte
}

func (q *Queries) GetPin(ctx context.Context, arg GetPinParams) (GetPinRow, error) {
	row := q.db.QueryRow(ctx, getPin, arg.DocType, arg.DocID)
	var i GetPinRow
	err := row.Scan(&i.Layout, &i.Locale, &i.Blocks)
	return i, err
}

const latestBlocks = `-- name: LatestBlocks :many
SELECT DISTINCT ON (b.template) b.template, b.version, b.texts, b.saved_at, u.name AS saved_by_name
FROM printing.blocks b JOIN iam.users u ON u.id = b.saved_by
ORDER BY b.template, b.version DESC
`

type LatestBlocksRow struct {
	Template    string
	Version     int32
	Texts       []byte
	SavedAt     pgtype.Timestamptz
	SavedByName string
}

func (q *Queries) LatestBlocks(ctx context.Context) ([]LatestBlocksRow, error) {
	rows, err := q.db.Query(ctx, latestBlocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestBlocksRow
	for rows.Next() {
		var i LatestBlocksRow
		if err := rows.Scan(
			&i.Template,
			&i.Version,
			&i.Texts,
			&i.SavedAt,
			&i.SavedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveBlocks = `-- name: SaveBlocks :one
INSERT INTO printing.blocks (template, version, texts, saved_by)
SELECT $1::text, coalesce(max(version), 0) + 1, $2::jsonb, $3::bigint
FROM printing.blocks WHERE template = $1::text
RETURNING version
`

type SaveBlocksParams struct {
	Template string
	Texts    []byte
	SavedBy  int64
}

func (q *Queries) SaveBlocks(ctx context.Context, arg SaveBlocksParams) (int32, error) {
	row := q.db.QueryRow(ctx, saveBlocks, arg.Template, arg.Texts, arg.SavedBy)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const snapshots = `-- name: Snapshots :many
SELECT part, data FROM printing.snapshots WHERE doc_type = $1 AND doc_id = $2 ORDER BY position
`

type SnapshotsParams struct {
	DocType string
	DocID   int64
}

type SnapshotsRow struct {
	Part int64
	Data []byte
}

func (q *Queries) Snapshots(ctx context.Context, arg SnapshotsParams) ([]SnapshotsRow, error) {
	rows, err := q.db.Query(ctx, snapshots, arg.DocType, arg.DocID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SnapshotsRow
	for rows.Next() {
		var i SnapshotsRow
		if err := rows.Scan(&i.Part, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
