// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
)

const createPin = `-- name: CreatePin :exec
INSERT INTO printing.pins (doc_type, doc_id, layout, locale) VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type CreatePinParams struct {
	DocType string
	DocID   int64
	Layout  int32
	Locale  string
}

func (q *Queries) CreatePin(ctx context.Context, arg CreatePinParams) error {
	_, err := q.db.Exec(ctx, createPin,
		arg.DocType,
		arg.DocID,
		arg.Layout,
		arg.Locale,
	)
	return err
}

const createSnapshots = `-- name: CreateSnapshots :exec
INSERT INTO printing.snapshots (doc_type, doc_id, part, position, data)
SELECT $1::text, $2::bigint, unnest($3::bigint[]), unnest($4::int[]), unnest($5::bytea[])
`

type CreateSnapshotsParams struct {
	DocType   string
	DocID     int64
	Parts     []int64
	Positions []int32
	Data      [][]byte
}

func (q *Queries) CreateSnapshots(ctx context.Context, arg CreateSnapshotsParams) error {
	_, err := q.db.Exec(ctx, createSnapshots,
		arg.DocType,
		arg.DocID,
		arg.Parts,
		arg.Positions,
		arg.Data,
	)
	return err
}

const getPin = `-- name: GetPin :one
SELECT layout, locale FROM printing.pins WHERE doc_type = $1 AND doc_id = $2
`

type GetPinParams struct {
	DocType string
	DocID   int64
}

type GetPinRow struct {
	Layout int32
	Locale string
}

func (q *Queries) GetPin(ctx context.Context, arg GetPinParams) (GetPinRow, error) {
	row := q.db.QueryRow(ctx, getPin, arg.DocType, arg.DocID)
	var i GetPinRow
	err := row.Scan(&i.Layout, &i.Locale)
	return i, err
}

const snapshots = `-- name: Snapshots :many
SELECT part, data FROM printing.snapshots WHERE doc_type = $1 AND doc_id = $2 ORDER BY position
`

type SnapshotsParams struct {
	DocType string
	DocID   int64
}

type SnapshotsRow struct {
	Part int64
	Data []byte
}

func (q *Queries) Snapshots(ctx context.Context, arg SnapshotsParams) ([]SnapshotsRow, error) {
	rows, err := q.db.Query(ctx, snapshots, arg.DocType, arg.DocID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SnapshotsRow
	for rows.Next() {
		var i SnapshotsRow
		if err := rows.Scan(&i.Part, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
