// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMailServer = `-- name: DeleteMailServer :execrows
DELETE FROM notification.mail_server
`

func (q *Queries) DeleteMailServer(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMailServer)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMailServer = `-- name: GetMailServer :one
SELECT host, port, security, username, password, from_address, base_url FROM notification.mail_server
`

type GetMailServerRow struct {
	Host        string
	Port        int32
	Security    string
	Username    string
	Password    []byte
	FromAddress string
	BaseUrl     string
}

func (q *Queries) GetMailServer(ctx context.Context) (GetMailServerRow, error) {
	row := q.db.QueryRow(ctx, getMailServer)
	var i GetMailServerRow
	err := row.Scan(
		&i.Host,
		&i.Port,
		&i.Security,
		&i.Username,
		&i.Password,
		&i.FromAddress,
		&i.BaseUrl,
	)
	return i, err
}

const getNotification = `-- name: GetNotification :one
SELECT user_id, kind FROM notification.notifications WHERE id = $1
`

type GetNotificationRow struct {
	UserID int64
	Kind   string
}

func (q *Queries) GetNotification(ctx context.Context, id int64) (GetNotificationRow, error) {
	row := q.db.QueryRow(ctx, getNotification, id)
	var i GetNotificationRow
	err := row.Scan(&i.UserID, &i.Kind)
	return i, err
}

const insert = `-- name: Insert :many
INSERT INTO notification.notifications (user_id, kind, doc_type, doc_id, job_id, actor_id)
SELECT unnest($1::bigint[]), $2, $3, $4, $5, $6
RETURNING id
`

type InsertParams struct {
	Users   []int64
	Kind    string
	DocType pgtype.Text
	DocID   pgtype.Int8
	JobID   pgtype.Int8
	ActorID pgtype.Int8
}

func (q *Queries) Insert(ctx context.Context, arg InsertParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, insert,
		arg.Users,
		arg.Kind,
		arg.DocType,
		arg.DocID,
		arg.JobID,
		arg.ActorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const list = `-- name: List :many
SELECT n.id, n.kind, n.doc_type, n.doc_id, n.job_id, n.created_at, n.read_at, u.name AS actor_name, d.number
FROM notification.notifications n
LEFT JOIN iam.users u ON u.id = n.actor_id
LEFT JOIN record.documents d ON d.id = n.doc_id AND d.doc_type = n.doc_type
WHERE n.user_id = $1 AND ($2::bigint IS NULL OR n.id < $2)
ORDER BY n.id DESC
LIMIT $3
`

type ListParams struct {
	UserID int64
	Before pgtype.Int8
	Lim    int32
}

type ListRow struct {
	ID        int64
	Kind      string
	DocType   pgtype.Text
	DocID     pgtype.Int8
	JobID     pgtype.Int8
	CreatedAt pgtype.Timestamptz
	ReadAt    pgtype.Timestamptz
	ActorName pgtype.Text
	Number    pgtype.Text
}

func (q *Queries) List(ctx context.Context, arg ListParams) ([]ListRow, error) {
	rows, err := q.db.Query(ctx, list, arg.UserID, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRow
	for rows.Next() {
		var i ListRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.DocType,
			&i.DocID,
			&i.JobID,
			&i.CreatedAt,
			&i.ReadAt,
			&i.ActorName,
			&i.Number,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mailable = `-- name: Mailable :many
SELECT n.id FROM notification.notifications n JOIN iam.users u ON u.id = n.user_id
WHERE n.id = ANY($1::bigint[]) AND u.email IS NOT NULL AND EXISTS (SELECT 1 FROM notification.mail_server)
`

// The notifications to email: their user has an address and the tenant a mail server.
func (q *Queries) Mailable(ctx context.Context, ids []int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, mailable, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllRead = `-- name: MarkAllRead :exec
UPDATE notification.notifications SET read_at = now() WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllRead(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, markAllRead, userID)
	return err
}

const markRead = `-- name: MarkRead :execrows
UPDATE notification.notifications SET read_at = coalesce(read_at, now()) WHERE id = $1 AND user_id = $2
`

type MarkReadParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) MarkRead(ctx context.Context, arg MarkReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recipient = `-- name: Recipient :one
SELECT email, locale FROM iam.users WHERE id = $1
`

type RecipientRow struct {
	Email  pgtype.Text
	Locale pgtype.Text
}

func (q *Queries) Recipient(ctx context.Context, id int64) (RecipientRow, error) {
	row := q.db.QueryRow(ctx, recipient, id)
	var i RecipientRow
	err := row.Scan(&i.Email, &i.Locale)
	return i, err
}

const saveMailServer = `-- name: SaveMailServer :exec
INSERT INTO notification.mail_server (host, port, security, username, password, from_address, base_url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET host = excluded.host, port = excluded.port, security = excluded.security,
    username = excluded.username, password = coalesce(excluded.password, notification.mail_server.password),
    from_address = excluded.from_address, base_url = excluded.base_url, updated_at = now()
`

type SaveMailServerParams struct {
	Host        string
	Port        int32
	Security    string
	Username    string
	Password    []byte
	FromAddress string
	BaseUrl     string
}

func (q *Queries) SaveMailServer(ctx context.Context, arg SaveMailServerParams) error {
	_, err := q.db.Exec(ctx, saveMailServer,
		arg.Host,
		arg.Port,
		arg.Security,
		arg.Username,
		arg.Password,
		arg.FromAddress,
		arg.BaseUrl,
	)
	return err
}

const unread = `-- name: Unread :one
SELECT count(*) FROM notification.notifications WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) Unread(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, unread, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
