// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
)

const next = `-- name: Next :one
INSERT INTO numbering.counters (doc_type, legal_entity_id, year, last) VALUES ($1, $2, $3, 1)
ON CONFLICT (doc_type, legal_entity_id, year) DO UPDATE SET last = numbering.counters.last + 1
RETURNING last
`

type NextParams struct {
	DocType       string
	LegalEntityID int64
	Year          int32
}

// Locks the counter row until the transaction ends, so a rollback gives the number back.
func (q *Queries) Next(ctx context.Context, arg NextParams) (int64, error) {
	row := q.db.QueryRow(ctx, next, arg.DocType, arg.LegalEntityID, arg.Year)
	var last int64
	err := row.Scan(&last)
	return last, err
}
