// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DataioFile struct {
	ID           string
	Name         string
	OwnerID      int64
	CreatedAt    pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	ExportKind   pgtype.Text
	ExportParams []byte
}
