// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFile = `-- name: CreateFile :exec
INSERT INTO dataio.files (id, name, owner_id, expires_at, export_kind, export_params) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateFileParams struct {
	ID           string
	Name         string
	OwnerID      int64
	ExpiresAt    pgtype.Timestamptz
	ExportKind   pgtype.Text
	ExportParams []byte
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) error {
	_, err := q.db.Exec(ctx, createFile,
		arg.ID,
		arg.Name,
		arg.OwnerID,
		arg.ExpiresAt,
		arg.ExportKind,
		arg.ExportParams,
	)
	return err
}

const deleteExpiredFiles = `-- name: DeleteExpiredFiles :many
DELETE FROM dataio.files WHERE expires_at < now() RETURNING id
`

func (q *Queries) DeleteExpiredFiles(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteExpiredFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFile = `-- name: GetFile :one
SELECT id, name, owner_id, created_at, expires_at, export_kind, export_params FROM dataio.files WHERE id = $1
`

func (q *Queries) GetFile(ctx context.Context, id string) (DataioFile, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i DataioFile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ExportKind,
		&i.ExportParams,
	)
	return i, err
}

const knownFiles = `-- name: KnownFiles :many
SELECT id FROM dataio.files WHERE id = ANY($1::text[])
`

func (q *Queries) KnownFiles(ctx context.Context, ids []string) ([]string, error) {
	rows, err := q.db.Query(ctx, knownFiles, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
