// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
)

const getLegalEntityValue = `-- name: GetLegalEntityValue :one
SELECT value FROM setting.legal_entity_values WHERE legal_entity_id = $1 AND key = $2
`

type GetLegalEntityValueParams struct {
	LegalEntityID int64
	Key           string
}

func (q *Queries) GetLegalEntityValue(ctx context.Context, arg GetLegalEntityValueParams) (string, error) {
	row := q.db.QueryRow(ctx, getLegalEntityValue, arg.LegalEntityID, arg.Key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getValue = `-- name: GetValue :one
SELECT value FROM setting.values WHERE key = $1
`

func (q *Queries) GetValue(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getValue, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const isLegalEntity = `-- name: IsLegalEntity :one
SELECT EXISTS (SELECT 1 FROM iam.org_units WHERE id = $1 AND kind = 'company')
`

func (q *Queries) IsLegalEntity(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, isLegalEntity, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const legalEntityValues = `-- name: LegalEntityValues :many
SELECT key, value FROM setting.legal_entity_values WHERE legal_entity_id = $1
`

type LegalEntityValuesRow struct {
	Key   string
	Value string
}

func (q *Queries) LegalEntityValues(ctx context.Context, legalEntityID int64) ([]LegalEntityValuesRow, error) {
	rows, err := q.db.Query(ctx, legalEntityValues, legalEntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LegalEntityValuesRow
	for rows.Next() {
		var i LegalEntityValuesRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLegalEntityValue = `-- name: SetLegalEntityValue :exec
INSERT INTO setting.legal_entity_values (legal_entity_id, key, value) VALUES ($1, $2, $3)
ON CONFLICT (legal_entity_id, key) DO UPDATE SET value = excluded.value
`

type SetLegalEntityValueParams struct {
	LegalEntityID int64
	Key           string
	Value         string
}

func (q *Queries) SetLegalEntityValue(ctx context.Context, arg SetLegalEntityValueParams) error {
	_, err := q.db.Exec(ctx, setLegalEntityValue, arg.LegalEntityID, arg.Key, arg.Value)
	return err
}
